dace/frontend/python/newast.py
MatMult operation was using as result type the type of the first operator. This has been changed to the output of numpy.result_type, as in all the other binary operations.
=> Result type for MatMult operation

dace/transformation/interstate/sdfg_nesting.py
Fix for nesting transformation:
- previously only source and sink node in the SDFG were considered and moved to the nested one. Now all the input/output node are considered
- change of transient property if an array has been moved to a Nested SDFG
=> Fix Nesting Transformation

diode/diode_rest.py
For some reason we had two implementations of `set_properties_from_json`: one in `dace.serialize`, and one in `diode.diode_rest`. Get rid of the latter, and fix the call that was breaking transformations in Diode.
=> Call dace.serialize.set_properties_from_json from Diode

dace/codegen/targets/cpu.py, tests/vla_test.py
This fixes an issue where symbolically-sized arrays are allocated on the stack. Instead of potentially overflowing the stack, a warning is emitted and the memory goes to the heap.
=> Avoid allocation of variable-length arrays if allocated on the stack

dace/codegen/compiler.py, dace/codegen/targets/cpu.py, dace/frontend/python/astutils.py, dace/frontend/python/newast.py, dace/frontend/python/parser.py, dace/graph/nodes.py, dace/properties.py, dace/sdfg.py, dace/serialize.py, dace/transformation/interstate/sdfg_nesting.py, tests/local_inline_test.py, tests/nested_symbol_partial_test.py, tests/nested_symbol_test.py, tests/properties_test.py
Allow nested SDFGs to be written once and have different symbol values based on their invocation.
=> Nested Symbols

dace/config_schema.yml, dace/frontend/common/op_repository.py, dace/frontend/python/newast.py, dacelibs/blas/nodes/matmul.py, dacelibs/blas/nodes/transpose.py
The frontend implementation functionality has been replaced by library nodes.
Remove this functionality, and port the "pure" expansion of transpose and matmul to the library nodes interface.
=> Remove frontend implementation functionality

dace/transformation/interstate/sdfg_nesting.py
NestSDFG now has the nested SDFG data names prepended with '__' to avoid possible name clashing due to appending '_in' and '_out'. This is a fix for #135
=> Fix for clashing Nested SDFG names

dace/codegen/codegen.py
if a target is already registered for CPU, use that as default instead of CPUCodegen, s.t. the code generator can be extended by users.
=> Enable Override of CPUCodegen with custom extensions.

dace/frontend/python/newast.py, dace/sdfg.py
This creates more meaningful transient array names in the most conservative way possible. 
Example 1 (softmax):
Example 2 (dTGL_test):
=> Python frontend: Try to replace transients with their assigned names

dace/sdfg.py, tests/sdfg_validate_names_test.py
There was a bug where `sdfg._start_state` was stored as an index, but read as a node. I've changed it to be stored as a node, since this is more robust to the SDFG changing.
=> Store node instead of index for starting state

dace/codegen/cppunparse.py, tests/intel_fpga/type_inference.py
There were errors in handling ternary operation (`cppunparse.py`).
The problem arises when the condition was expressed as a composition of boolean expression. The `__BoolOp` function was not properly handling the case in which type inference is requested.
I've slightly changed the `interleave` function.
Added test for intel_fpga.
=> Ternary operation code generation

dace/codegen/targets/xilinx.py
When creating Xilinx OpenCL kernels, we were concatenating scalar arguments with symbol arguments. It seems symbol arguments sometimes include scalar arguments despite the `include_scalar_arguments` flag being set to `False` (and/or the other way around).
Work around this by deduplicating arguments in the Xilinx codegen.
=> Double argument in Xilinx kernels

dace/codegen/targets/cpu.py, tests/nested_sdfg_scalar_test.py
Now obeying SDFG semantics - if the internal node is an array, generate a pointer. If it's a scalar, generate a scalar.
=> Fix nested SDFG size-1 connectors

dace/codegen/targets/xilinx.py
While compiling and running on Xilinx FPGA I ran into the following issue:
```
terminate called after throwing an instance of 'hlslib::ocl::ConfigurationError'
what():  Failed to open program file "/home/burgerm/thesis_dace/tasks/blas/level1/axpy/.dacecache/saxpy_perf/buildsaxpy_perf_hw.xclbin".
```
There is a `/` missing between `...build` and `$PROGRAM_NAME` .The small change should fix it.
=> Fix missing slash in fpga codegen

dace/memlet.py, dace/sdfg.py, tests/codegen/concurrent_subgraph_test.py
This fixes a bug in `concurrent_subgraphs` that would result in code for subgraphs being generated more than once.
=> Bugfix: duplicate map code produced

diode/webclient/renderer.js
- Nodes and edges can both be dragged
- Moving/panning of the view was moved from primary mouse button to secondary mouse button (for now?)
- Movement of nodes is restricted to remain within their parent element, e.g. state or nested SDFG
=> SDFV: Draggable graph elements

diode/webclient/renderer.js
Dragging a state with collapsed nested SDFGs inside caused null references when trying to move the nested SDFG's contents. This has been resolved with an additional check.
Additionally the way the change in mouse position represented in canvas coordinates has been changed to a more proper and robust solution using the existing coordinate conversion methods.
=> SDFV: Critical dragging bugfix & change in dragging distance calculation

dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py
We've had indeterminism in the FPGA code generators, which leads to recompiling when it's not necessary, and which could potentially lead to sporadic behavior.
I've now made sure to reorder all arguments according to their name.
The reason why this is not done centrally is because the arguments can vary depending on the context, and there might sometimes be mixes between array and scalar arguments.
It could be prettier, but it's better than before :-)
=> Order FPGA Arguments

dace/codegen/targets/fpga.py
The variable `nodedesc` was not initialized in this scope and threw an error.
=> FPGA codegen, fix error message for different veclen to same memory

dace/codegen/targets/intel_fpga.py, tests/intel_fpga/name_too_long.py, tests/intel_fpga_test.sh
Intel FPGA OpenCL doesn't allow kernel names longer than 61 characters. Fail in DaCe with an explicit error when this occurs in practice.
https://www.intel.com/content/www/us/en/programmable/documentation/bhg1517418195706.html#dhf1517418905976
=> Fail if kernel name is too long

dace/codegen/targets/fpga.py
This PR fixes two things:
- If a loop is fully degenerate, don't insert pipeline pragmas, since no loops are actually emitted.
- When checking if a loop is innermost, don't take degenerate loops into account.
=> Don't pipeline degenerate loops

dace/library.py
Small fix for the registration of library transformations:
- `isinstance` to `issubclass`
- Correctly show class name in error message
=> Fix library transformation registration

.style.yapf
This is picked up automatically when yapf'ing files with `dace` as the work directory.
=> yapf style file

dace/config_schema.yml, dace/frontend/operations.py
If you install [`tqdm`](https://github.com/tqdm/tqdm) in you dace python environment you will be able to see a live status bar during profiling.
=> Add support for tqdm status bar to dace profiler

dace/frontend/python/newast.py, tests/numpy/variable_reassignment_test.py
The purpose is to allow code like the following to work:
```python
@dace.program
def reassign(a: dace.float64[1]):
s = 0.0
s = 1.0
```
The solution is to interpret the second statement `s = 1.0` as `s[0] = 1.0` or `s[:] = 1.0`.
However, redefinition of arrays is still now allowed, i.e., this only works with arrays of shape (1, ).
=> Allowing reassignment of arrays of shape (1, )

dace/properties.py, dace/transformation/interface/vscode/__init__.py, dace/transformation/interface/vscode/__main__.py, dace/transformation/optimizer.py, dace/transformation/pattern_matching.py, dace/transformation/subgraph/gpu_persistent_fusion.py
This adds a new module that serves as an interface between DaCe and its VSCode extension.
The interface is by default started as a deamon from within the VSCode extension and then serves HTTP requests to facilitate interaction between the two components.
As part of this, (de)serialization to and from JSON has been added to the Transformation class.
=> VSCode interface API module

dace/frontend/python/newast.py, dace/transformation/interstate/state_fusion.py, tests/transformations/state_fusion_node_merge_test.py
State fusion has the following code for relaxing checking RW/WW dependencies:
```python
check_strict = len(first_cc)
for cc_output in first_cc_output:
out_nodes = [
n for n in first_state.sink_nodes() if n in cc_output
]
if len(out_nodes) > 1:
continue
for node in cc_output:
if (next((x for x in second_input if x.label == node.label),
None) is not None):
check_strict -= 1
break
```
The relaxation is supposed to be applied when there is a single sink node in the first state, i.e. out_nodes has length of 1. However, it is possible (see #274) that cc_output has two access nodes, one connected to the other (A -> B). In this case, the existence of a single sink node will be correctly detected (B), but then the other node (A) will trigger relaxing the checks if an access node of the same data …
=> Fixing relaxation of checks in state fusion

dace/transformation/interface/vscode/__main__.py
This adds docstrings to the JSON being sent out by the module. VSCode uses these docstrings to formulate the tooltips when hovering over a specific transformation.
=> VC-INTERFACE: Added docstrings to the transformation listings

dace/frontend/python/newast.py, dace/runtime/include/dace/types.h, dace/runtime/include/dace/xilinx/math.h, tests/numpy/pi_test.py
This fixes an issue where the Python frontend is used with constants in modules, such as `math.pi`, and eliminates warnings from GPU and FPGA compilation.
=> Better support for pi, constexpr, and other constants in modules

dace/codegen/sdfgcc.py
Should close issue #256.
I added -o support via sdfg.compile(path/filename).
I rewrote the parsing of the command line arguments with argparse.
new usage:
sdfgcc <PATH TO SDFG FILE> [-o <OUTPUTPATH>]
Directories in OUTPUTPATH need to exist beforehand.
=> SDFGCC: added -o support

dace/runtime/include/dace/copy.h
Memcpy is supported by the hipcc compiler, but seems to block conversion from stack arrays into registers arrays in some cases.
=> Disable Memcpy in HIP Kernel Code

dace/symbolic.py
Symbols that are of type `long long` or any other integer type apart from `int` are currently generated without the assumption `Integer=True`. The purpose of this PR is to fix this issue.
=> Fix for integer (but not `int`) symbols

dace/frontend/python/newast.py, dace/frontend/python/parser.py, tests/python_frontend/test_propagate_strict.py
I would like this for a test in daceml.
=> Propagate strict argument of to_sdfg when nested dace programs are parsed

dace/codegen/instrumentation/papi.py, dace/codegen/targets/cpu.py, dace/codegen/targets/cuda.py, dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/mpi.py, dace/codegen/targets/target.py, dace/codegen/targets/xilinx.py, dace/sdfg/infer_types.py, dace/sdfg/propagation.py, dace/sdfg/scope.py, dace/sdfg/state.py, dace/sdfg/utils.py, dace/transformation/dataflow/gpu_transform_local_storage.py, dace/transformation/dataflow/map_fission.py, dace/transformation/helpers.py, dace/transformation/interstate/gpu_transform_sdfg.py, dace/transformation/interstate/transient_reuse.py, dace/transformation/subgraph/helpers.py, dace/transformation/subgraph/reduce_expansion.py, dace/transformation/transformation.py, tests/nest_subgraph_test.py, tests/persistent_map_cudatest.py, tests/persistent_tb_map_cudatest.py
Replaces `scope_dict` (which had two functionalities) with `scope_dict` (parent scope node mapping) and `scope_children`.
=> Style Cleanup #2: scope_dict

dace/codegen/targets/framecode.py, dace/frontend/python/newast.py, dace/frontend/python/parser.py, dace/properties.py, dace/sdfg/analysis/scalar_to_symbol.py, dace/sdfg/propagation.py, dace/sdfg/sdfg.py, dace/subsets.py, dace/symbolic.py, dace/transformation/helpers.py, dace/transformation/interstate/state_fusion.py, tests/codegen/control_flow_detection_test.py, tests/python_frontend/arithmetic_conversions_test.py, tests/python_frontend/assignment_statements_test.py, tests/python_frontend/binop_replacements_test.py, tests/python_frontend/identifiers_and_keywords_test.py, tests/python_frontend/indirection_with_scalars_test.py, tests/python_frontend/line_structure_test.py, tests/python_frontend/loops_test.py, tests/python_frontend/nested_name_accesses_test.py, tests/python_frontend/power_operator_test.py, tests/python_frontend/subscript_regression_test.py, tests/python_frontend/test_propagate_strict.py, tests/python_frontend/transients_test.py, tests/sdfg/scalar_to_symbol_test.py
A global SDFG pass that converts SDFG scalars and arrays of size 1 to inter-state symbols.
=> Scalar-to-Symbol Promotion

dace/frontend/python/replacements.py, tests/numpy/binop_broadcasting_test.py
Broadcasting with dim 1 matching dim None previously resulted in the output shape having `None` inside of it. This PR fixes that.
=> Fix bug in numpy broadcasting

dace/dtypes.py, dace/frontend/python/parser.py, dace/frontend/python/replacements.py, tests/numpy/nested_call_subarray_test.py, tests/numpy/reductions_test.py
Reductions rely on `Subset.pop`, but this doesn't work correctly when reducing along all axes. It instead reduces along the last axes.
This PR bypasses that issue.
=> Fix reductions when reducing along all axes and allow local SDFGs to be called

dace/codegen/targets/intel_fpga.py, samples/fpga/gemm_fpga_stream.py
Some FPGA samples still use ancient ways of creating SDFGs. Update the `gemm_fpga_stream.py` sample to a more modern version.
Along the way, fix a bug in the Intel FPGA codegen :-)
=> Modernize FPGA GEMM streaming example

dace/sdfg/sdfg.py, dace/sdfg/state.py, dace/transformation/__init__.py, dace/transformation/dataflow/prune_connectors.py, dace/transformation/helpers.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/loop_unroll.py, dace/transformation/transformation.py, tests/python_frontend/transients_test.py
Fix issues found in both transformations by applying it to Polybench and LULESH SDFGs.
Move `read_and_write_sets` into `SDFG` and `SubgraphView`. Add symmetric `remove_symbol` function to `SDFG`.
=> Fixes to PruneConnectors and LoopToMap

dace/frontend/python/newast.py, dace/subsets.py
When a range ends up empty after executing `subsets.Range.pop`, it keeps its original last dimension. This may lead to erroneous computation of the inner and outer indices in `ProgramVisitor._add_dependencies`. To alleviate the problem, `subsets.Range.pop` must default to a unit range `[(0, 0, 1)]` when popping all dimensions. If such behavior is not appropriate for all cases where `subsets.Range.pop` is called, then `ProgramVisitor._add_dependencies` must be rewritten to compute the inner and outer indices in a different manner.
=> Issues with subsets.Range.pop

dace/sdfg/sdfg.py, dace/transformation/interstate/loop_detection.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/loop_unroll.py, dace/transformation/interstate/state_elimination.py, dace/transformation/interstate/state_fusion.py, tests/transformations/loop_to_map_test.py
Extend LoopToMap:
- Allow the iteration variable to be used later in the state machine if it is first reassigned to something else (so that we don't have to output the end value after executing the map).
- Allow overlap between read and write sets if the container is read and written at exactly the same index at exactly one memory location.
Fixes to StateAssignElimination:
- Fix a typo in `apply`
Fix to StateFusion:
- Don't allow fusion when a free symbol of the second state is written as a data container in the first.
=> Improve LoopToMap and StateAssignElimination and StateFusion

dace/codegen/compiled_sdfg.py
The `capture_output` argument to `subprocess.run()` wasn't added until Python 3.7 [https://docs.python.org/3.7/library/subprocess.html#subprocess.run](url)
This patch reverts the call to be functional in Python 3.6
=> Fixed wrong arguments to Python 3.6 version of subprocess.run()

dace/sdfg/propagation.py, dace/transformation/interstate/branch_annotation.py, dace/transformation/interstate/branch_detection.py
- Corrects wrongful removal of iteration variables from the iteration variable stack by moving the iteration variable stack to the traversal's own state instead of keeping it global.
- Make branch detection correctly detect full merges in cases where there are two branches with one of the branch's only state itself being the branch construct's full merge state.
=> Fixes nested loop tracking and branch annotation in state propagation

dace/transformation/interstate/loop_annotation.py, dace/transformation/interstate/loop_detection.py, dace/transformation/interstate/loop_peeling.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/loop_unroll.py
- Enable detection of for loop constructs with more than 1 init edge going in to the guard.
- Let `find_for_loop` return all states immidiately before the loop, as well as the last loop state, to generalize this functionality and move it out of the transformations using it (loop peeling, unroll).
=> Allows loop detection to correctly handle for loops with > 1 init edge

dace/frontend/python/newast.py
When adding inner scope dependencies that are scope variables (i.e., the SDFG is neither top-level nor "leaf"), an appropriately "squeezed" connector must be generated. However, dimensions of size 1 must not be squeezed if they belong to the set of "inner dimensions." This is a corner case that occurs when the dependency comes out of a map where one of the dimensions has a range of length 1, e.g., as in issue #352. This PR fixes this bug.
=> Fix for missing inner indices

dace/memlet.py, dace/sdfg/propagation.py, dace/sdfg/sdfg.py
Also provides a short fix for a potential reference to an undefined variable when failing a validation in SDFG's `apply_transformations_repeated`.
=> Fix invalid subsets propagated out of nested SDFGs if symbols not defined outside NSDFG

tutorials/codegen.ipynb
Found two typos in the codegen tutorial.
=> Typos in codegen tutorial

dace/codegen/targets/framecode.py, dace/sdfg/graph.py
The function 'all_nodes_between(..)' is only ever used in framecode.py. There the 'begin' node is now added after the function call so this commit doesn't break anything.
=> Removes element 'begin' from 'all_nodes_between(..)'.

dace/codegen/targets/cpp.py, dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py, samples/fpga/gemm_fpga_systolic.py, tests/intel_fpga/simple_systolic_array.py
Modernize the systolic GEMM sample, and fix a handful of issues that popped up along the way:
- Handling of `StreamArray` in Xilinx wrongly removed the index
- Stream buffer sizes was not being symbolically evaluated before checking if the value is compile-time fixed
- Processing element unrolling for Intel FPGA made a wrong assumption
- Intel codegen should actually use the memlet name when generating channel accesses
- Intel codegen was defining memlets accessing stream arrays as stream arrays, when they should be streams
- Added missing undefines causing warnings
=> Modernize Systolic GEMM and fix issues along the way

dace/__init__.py, dace/codegen/compiler.py, dace/codegen/targets/framecode.py, dace/libraries/blas/environments/cublas.py, dace/libraries/blas/environments/intel_mkl.py, dace/libraries/blas/environments/openblas.py, dace/libraries/standard/environments/cuda.py, dace/library.py
This PR adds a dependency field to dace environments, which is a list of environments.
When generating the framecode, the initialization and exit code ordering respects the dependencies.
This is required for a change in daceml: https://github.com/spcl/daceml/pull/30
=> Add dependency support to environments

dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py, tests/fpga/multiple_veclen_conversions.py, tests/intel_fpga_test.sh, tests/xilinx_test.sh
Gearbox definitions are code generated in an external file.
FPGA kernels have only forward declaration.
In this way, If the same converter is used by multiple FPGA kernels, we don't have compiler errors (symbols defined multiple times)
=> IntelFPGA: gearboxing with multiple kernels

dace/codegen/cppunparse.py, dace/codegen/targets/cpp.py, dace/codegen/targets/fpga.py, dace/sdfg/nodes.py, dace/sdfg/state.py, tests/fpga/pipeline_scope.py
- Resolves #548 
- Resolves a bug in cppunparse: if a symbol is already defined, there is no need to re-define it (or perform type inference when needed). Before, this was causing the re-definition of already defined variables.
=> Pipeline scope: user can define additional variables 

dace/sdfg/propagation.py, dace/transformation/dataflow/local_storage.py, dace/transformation/dataflow/strip_mining.py
Bugfix:
- memlets now show the correct volume/num_accesses
- fixed by calling `.simplify()` in `strip_mining` and `propagate_subsets`
LocalStorage:
- no also simplifies the array size
- prefix property
- create_array property
=> bugfix: memlet propagation, LocalStorage: added prefix and create_array properties

dace/codegen/codegen.py, dace/codegen/compiled_sdfg.py, dace/frontend/python/newast.py, dace/libraries/blas/nodes/batched_matmul.py, dace/libraries/blas/nodes/gemm.py, dace/properties.py, dace/sdfg/__init__.py, dace/sdfg/infer_types.py, dace/sdfg/sdfg.py, dace/sdfg/utils.py, dace/transformation/interstate/sdfg_nesting.py, tests/inline_nonsink_access_test.py, tests/library/codelibnode_test.py, tests/numpy/retval_test.py
=> Various fixes for GPU code generation and miscellaneous things

dace/libraries/blas/nodes/dot.py, tests/library/blas_dot_test.py
The return value of `cblas_?dot` is supposed to be a scalar and not a pointer.
Fix by changing the OpenBLAS expansion tasklet code from `_result = cblas ...` to `_result[0] = cblas ...`.
`_result` is an array of size 1.
=> Fix for BLAS dot library node

dace/frontend/python/astutils.py, dace/frontend/python/memlet_parser.py, tests/numpy/negative_indices_test.py
Adds support to the Python frontend for accessing arrays with constant negative indices, e.g. `A[-2]`.
This PR does not include support for non-constant negative indices, e.g. `A[-i]`, where `i` is a map index variable or something similar.
=> Support for constant negative indices

dace/frontend/python/replacements.py, tests/numpy/array_creation_test.py
Adds support for the following NumPy array creation routines:
- empty
- empty_like
- ones
- ones_like
- zeros
- zeros_like
- full
- full_like
- copy
- identity
=> NumPy array creation routines

dace/frontend/python/newast.py, dace/frontend/python/replacements.py, tests/numpy/ndarray_attributes_methods_test.py
=> Add support for various ndarray attributes and methods

dace/transformation/dataflow/redundant_array.py
The redundant array transformations should always work when the shape of the array to-be-removed is a subset of the shape of the array to-stay:
- RedundantSecondArray now checks that output shape is a subset of input shape in strict mode.
- RedundantArray now doesn't create Views when the input shape is a subset of the output shape. Instead, it uses subset composition, exactly the same way as RedundantSecondArray.
=> Improvements to Redundant Array transformations.

dace/codegen/targets/cpp.py, tests/copynd_test.py
This PR fixes the calculation of strides for 1D strided copies. Examples of copies that do not currently work properly in master:
- `q[1:N - 1, 0] = v[0, 1:N - 1]`
- `v[0, 1:N - 1] = q[1:N - 1, 0]`
=> Fixing calculation of strides for 1D strided copies.

dace/transformation/interstate/sdfg_nesting.py
While nesting, memlets are updated according to the new array names.
Previously, this was not considering the case in which the memlet was referring to the destination array
=> Fix memlet update while nesting

dace/codegen/targets/intel_fpga.py
When a tasklet uses `pow`, it is code generated by using dace namespaces `dace::math::pow`
OpenCL does not support namespaces, therefore we intercept this in OpenCLDaceKeywordRemover before actually generating the code.
=> Intel fpga codegen pow

dace/sdfg/scope.py, dace/transformation/dataflow/map_fusion.py, dace/transformation/dataflow/redundant_array.py, dace/transformation/helpers.py, tests/transformations/mapfusion_data_races_test.py, tests/transformations/redundant_copy_data_races_test.py
The PR attempts to address an issue that occurs with the following code:
```python
@dace.program
def rw_data_race(A: dace.float32[10, 10]):
A2 = A.copy()
A[1:-1, 1:-1] = A2[:-2,:-2] + A2[2:,2:]
```
The SDFG with fused states but not redundant copies removed will approximately have the following flow: 
``` 
A --> A2 --> tmp1 --> Map Entry --> i, j -----> Tasklet --> i+1, j+1 --> Map Exit --> A
--> tmp2 --> Map Entry --> i+2,j+2 --> Tasklet
```
If `tmp1` and `tmp2` are removed, then the only thing holding the "double buffering" scheme is `A2`. However, RedundantSecondArray will trigger and remove it as well. In this case, a data race is produced due to the offsets accesses to A inside the Map. This PR attempts to fix this issue.
=> Application of Redundant(Second)Array leads to data races

dace/libraries/standard/nodes/reduce.py, dace/transformation/dataflow/redundant_array.py, tests/transformations/redundant_copy_test.py
This PR attempts to address issue #575. The fix is done through `Redundant(Second)Array` instead of `Range.compose`, because it becomes impossible to infer the correct composition when reaching the innermost Memlets, where subsets are `Indices`.
=> Better subset composition

dace/libraries/blas/nodes/matmul.py, dace/sdfg/sdfg.py, dace/subsets.py, dace/transformation/dataflow/map_fusion.py, dace/transformation/dataflow/redundant_array.py
What the title says pretty much. If the matched edge `A ----> B` has WCR, then the new edge `A0 ----> B` or `A ----> B0` (depending on which array is removed) and the corresponding memlet path must inherit the WCR.
I am also addressing in this PR a small bug in MapFusion, an issue with SDFG.free_symbols considering nested SDFG defined symbols to be undefined, and an issue where popped indices in RedundantArray are not pushed back in the correct order, an output shape issue with MatMul (GEMM), and an issue with MatMul output edge having WCR.
=> RedundantArray transformations copy WCR to new edge and memlet path

dace/transformation/interstate/sdfg_nesting.py
- When inlining, if inner/outer strides are equal, don't check for unsqueezing, that could add unneeded views
- When Nesting, removes from the parent SDFG the symbols that are defined in the nested one
=> Nesting and Inline fixes

dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py, dace/transformation/interstate/fpga_transform_state.py, dace/transformation/interstate/sdfg_nesting.py, tests/fpga/reshape_view_fpga.py, tests/intel_fpga_test.sh, tests/xilinx_test.sh
This PR provides adds additional support for views in FPGA (solves #612):
- deals with views while nesting:
- views are kept as transient
- their storage type is the same as the viewed node
- generates proper device code (for example, views with Global storage must not be generated on the host, or appear as kernel parameters)
- special attention for Intel FPGA codegeneration
-  adds tests for view on FPGA
=> Support FPGA view

dace/codegen/targets/intel_fpga.py
When generating argument for multiple Nested SDFGs, do not add more indirections than needed (`*`)
=> Intel fpga nested sdfg arguments

dace/frontend/python/memlet_parser.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/memlet.py, dace/sdfg/sdfg.py, dace/sdfg/validation.py, dace/subsets.py, dace/symbolic.py, dace/transformation/dataflow/map_fusion.py, dace/transformation/dataflow/redundant_array.py
This PR attempts to address the fact that symbols are being converted to string and back to symbols again in the whole DaCe stack. This is a serious issue because important symbolic assumptions are lost. A characteristic example is the NPBench benchmark `stockham_fft` which has symbolic sizes with either powers or logarithms. This sample can only work with the array sizes being explicitly defined as positive integers and the loop-indices implicitly defined as non-negative integers.
=> Consistent symbols

dace/codegen/targets/cuda.py, dace/runtime/include/dace/math.h, dace/symbolic.py, dace/transformation/dataflow/redundant_array.py, tests/copynd_test.py, tests/transformations/redundant_reshape_views_test.py
This PR addresses the issue of pseudo-2D copies. These are copies where there are elements from only one dimension copied, which is not the last one. Therefore, the stride is greater than 1. These copies must be handled with `cudaMemcpy2D` and not `cudaMemcpy`.
=> Fix cudaMemcpy(2D) for strided copies

dace/codegen/targets/cpp.py, dace/codegen/targets/fpga.py, dace/libraries/blas/nodes/gemm.py, dace/symbolic.py, tests/fpga/gemm_fpga.py, tests/intel_fpga_test.sh, tests/xilinx_test.sh
This PR adds a GEMM expansion for FPGA and some small fixed for Xilinx backend:
- the expansion uses a 1D systolic array architecture, with tunable number of PEs and Tile sizes
- for Xilinx, in the generated code:
- when writing to an array interface we refer the `_out` array
- we don't generate useless dep pragmas
=> FPGA: Gemm libnode expansion

dace/codegen/prettycode.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cuda.py, dace/codegen/targets/framecode.py, dace/config.py, dace/data.py, dace/libraries/blas/blas_helpers.py, dace/libraries/blas/environments/intel_mkl.py, dace/libraries/blas/nodes/batched_matmul.py, dace/libraries/blas/nodes/gemm.py, dace/library.py, dace/sdfg/graph.py, dace/transformation/auto_optimize.py, dace/transformation/interstate/sdfg_nesting.py, tests/codegen/allocation_lifetime_test.py, tests/config_test.py, tests/library/einsum_blas_test.py, tests/library/matmul_cudatest.py
- Make MKL expansion check their storage types before expanding
- Properly set the ``__dace_cuda_stream`` variable in codegen (in particular when `max_concurrent_streams==-1`)
- Fix einsum to BMM expansion
- Fix accessing persistent GPU global memory in kernels
- Connect src->sink edges in InlineSDFG
- Allow ``init_code`` and ``finalize_code`` properties of environments be callable, they take the sdfg that code is being generated for as an argument.
=> Gemm related fixes

dace/codegen/dispatcher.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/fpga.py, dace/codegen/targets/xilinx.py
Centralize generation of references to `ArrayInterface` to make sure we always follow the same procedure when possible.
=> More ArrayInterface Fixes

dace/codegen/targets/xilinx.py, dace/runtime/include/dace/xilinx/host.h
Fix the dependency pragma to correctly reference `ArrayInterface` names, and change the included hlslib OpenCL header for Xilinx.
=> Dependency pragma and hlslib header

dace/sdfg/sdfg.py, dace/transformation/interstate/fpga_transform_state.py
Don't copy transients to/from the FPGA that are never used outside the FPGA kernel.
=> Remove useless FPGA copies

dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py
* Improve handling of global scalars, as this occurs with some frontends.
* Don't distinguish between array, scalar, and symbol arguments, in how they are handled across the FPGA codegen.
* Deduplicate kernel arguments centrally, instead of all over the FPGA codegens.
* Detect and fail if the kernel expects scalar outputs from the kernel, as this is not currently supported.
* Update how RTL tasklets are called to use the specific subgraph parameters
=> Streamline FPGA kernel argument generation

dace/codegen/targets/fpga.py
- Sort arguments by name, _then_ by interface ID (if available)
- Also sort top level transients to be allocated
=> Also order FPGA arguments by interface ID

dace/transformation/interstate/sdfg_nesting.py
I haven't found an actual bug caused by this, but the current code is probably wrong since it compares strings with accessnodes
=> Update expression for unused connectors in InlineSDFG

dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py, dace/sdfg/utils.py
- Move memory bank assignment to kernel generation instead of array allocation.
- Make sure that bank assignments are consistent
- Make sure that bank assignment is present in the outermost scope, where the node is allocated
=> Memory bank assignment for nested SDFGs

dace/codegen/targets/cpu.py, dace/codegen/targets/fpga.py, dace/codegen/targets/xilinx.py, dace/transformation/auto_optimize.py, dace/transformation/dataflow/stream_transient.py, dace/transformation/interstate/fpga_transform_state.py, dace/transformation/interstate/sdfg_nesting.py, tests/intel_fpga_test.sh, tests/transformations/mapfusion_fpga.py, tests/xilinx_test.py
Just by removing an unnecessary reference in emitting code-to-code memlets, we support the most common cases of CodeNode->Tasklet in OpenCL also. `FPGATransformSDFG` has been relaxed accordingly.
By doing this, several minor issues came up due to the auto-optimization tests triggering `FPGATransformSDFG` in more scenarios, which have been fixed:
=> Support CodeNode->Tasklet and AccessNode->MapEntry memlets on FPGA

dace/codegen/targets/xilinx.py
In part of the Xilinx codegen, a trailing comma is mistakingly generated in some cases (if "parameters" is empty), which breaks the syntax of the generated code.
This fix ensures, that no such trailing comma is generated.
Example of such a broken syntax:
`auto kernel_rtl_ma_0_1_26 = program.MakeKernel("rtl_ma_0_1_26_top", ).ExecuteTaskFork();`
=> Fix Xilinx codegen trailing comma

dace/codegen/targets/intel_fpga.py
- Mangle module names
- define constants only once
=> Intel FPGA: Codegen fixes

dace/sdfg/sdfg.py, dace/transformation/dataflow/local_storage.py, dace/transformation/dataflow/mapreduce.py, dace/transformation/dataflow/strip_mining.py
StripMining:
- for tiling_type: number_of_tiles, now creates the correct tile size.
SDFG.free_symbols:
- now correctly computes the free_symbols.
- the free_symbols of data descriptors are not needed as they are covered in the free_symbols of each state.
SDFG.add_datadesc:
- add free symbols to the SDFG global symbol storage not needed
MapReduceFusion: 
- delete data descriptors that are not used anymore
LocalStorage:
- sdfg.add_array -> sdfg.add_transient
=> Bugfixes: StripMining, sdfg.free_symbols

dace/data.py, dace/dtypes.py
The property `dtype` of the class `Data` and its subclasses is a `typeclass` property. The class `typeclass` seems to be constrained to a set of predefined types which are listed in `dace.dtypes`. These predefined values are also used for reconstructing the `dtype` property from JSON. This creates a proper enum for these options and provides them to the `dtype` property as choices.
Benefit: This allows for easier editing of a data container's data type since it removes the chance of typos and the need for additional string parsing after user input.
=> Give the Data class' property 'dtype' the correct enum choices

dace/sdfg/nodes.py, dace/serialize.py, dace/transformation/transformation.py
Provide a general deserialized representation for unregistered objects such that they can be re-serialized without any loss of information and handled without causing exceptions.
In particular: keep transformation histories intact when they contain unregistered transformations, and don't fail on deserializing SDFGs with unregistered LibraryNodes.
=> Improve handling of unregistered objects and custom/external extensions like transformations and library nodes

dace/transformation/dataflow/prune_connectors.py, dace/transformation/interstate/sdfg_nesting.py
Improvements to InlineSDFG:
- InlineSDFG should not match when the nested SDFG has "unused" connectors, i.e., connectors without a corresponding access node inside the nested SDFG. If the transformation matches, then StopIteration will be raised when applying.
- PruneConnectors should match whenever it is possible to remove at least one connector.
=> Inline sdfg improvements

dace/data.py, dace/dtypes.py, dace/properties.py, dace/registry.py, dace/sdfg/nodes.py, dace/sdfg/sdfg.py, dace/sdfg/state.py, dace/transformation/dataflow/copy_to_device.py, dace/transformation/dataflow/streaming_memory.py, dace/transformation/dataflow/strip_mining.py, dace/transformation/subgraph/composite.py, dace/transformation/subgraph/subgraph_fusion.py
If a value not registered in an `EnumProperty`'s choices is deserialized, it is deserialized as `Undefined` in the corresponding enum property's data type. The original value is remembered, such that it can be restored upon subsequent re-serialization. This means that custom/unregistered values can be used for enum properties without causing errors, while remaining intact through de-/re-serialization of the SDFG.
=> Add enum properties and enums which are safe from custom values

dace/sdfg/propagation.py
Memlet propagation also propagates loop variables as state annotations since PR #421. However, when applying Loop2Map (and probably other transformations that remove states or heavily modify the state machine of an SDFG) and "state propagation" subsequently errors appear. This is because state annotations from previous calls to memlet propagation are not reset. This PR introduces a shallow reset method that is called at the beginning of `propagate_memlets_sdfg`.
=> Reset loop-related state annotations

dace/transformation/interstate/state_fusion.py
When fusing state, it is possible that the effectively removed state is the SDFG's start state. This is normally OK since the start state is automatically re-computed in the next call to the property. However, the property considers the case where there are multiple candidate start states. In those cases, it keeps the old start state, which may have been removed. The apply method of StateFusion now checks for this case and manually sets the SDFG's start state to be the state that was not removed by the transformation.
=> Fix for StateFusion rendering the start state of the SDFG invalid

dace/codegen/targets/xilinx.py
Vitis throws a warning during hardware emulation, that it cannot find `emconfig.json`. This environment variable correctly points Vitis to the file.
=> Added environment variable for finding emconfig

dace/codegen/compiled_sdfg.py, dace/codegen/cppunparse.py, dace/codegen/targets/common.py, dace/data.py, dace/dtypes.py, dace/frontend/python/newast.py, dace/frontend/python/parser.py, dace/frontend/python/replacements.py, dace/symbolic.py, tests/codegen/sve/map_test.py, tests/python_frontend/constant_and_keyword_args_test.py, tests/python_frontend/global_folding_test.py, tests/python_frontend/lambda_test.py
=> Python frontend: Better support for arguments

dace/runtime/include/dace/math.h
Add bitwise functions:
- bitwise_and
- bitwise_or
- bitwise_xor
- bitwise_invert
- right_shift
- left_shift
=> Add bitwise operators to runtime for SymPy compatibility

dace/sdfg/nodes.py
Scope nodes without proper exit/entry reference are wrongfully deserialized as `SerializableObject`. This makes sure they are still deserialized as proper scope nodes.
=> Fix deserialization of scope nodes

setup.py
Networkx 2.5 is required for `transitive_closure_dag`
=> Install networkx>=2.5

dace/codegen/CMakeLists.txt, dace/codegen/targets/fpga.py, dace/codegen/targets/xilinx.py, tests/fpga/kernels_detection.py
I've consolidated the `.cfg`/`.ini` file to include both the DRAM bank assignments and the streaming interface assignments between kernels in `xilinx.py`.
=> Change DRAM bank assignment syntax to work with Vitis 2021.1

dace/sourcemap.py
Instead of collecting the source file names in a set, we collect them in a list as it will be sorted by the node occurrence in all_nodes_recursive(). This allows better results in vscode for jumping from C++ to a single source file. Even though changing from a set to a list is less efficient, this won't create a noticeable performance impact as the number of source files is expected to be small.
=> Sends vscode a more prioritised/sorted sourcefile list

dace/codegen/instrumentation/report.py, dace/codegen/targets/fpga.py, tests/fpga/kernels_detection.py
Example report:
```
Instrumentation report
SDFG Hash: 26b82bdad82332901ca002d8ec19e6da72d40c49754655422032705ba2e2bf3f
---------------------------------------------------------------------------
Element        Runtime (ms)
Min            Mean           Median         Max
---------------------------------------------------------------------------
SDFG (0)
|SDFG gemm:
|              3572.881       3572.881       3572.881       3572.881
|-State (0)
| |State MapState:
| |            3572.867       3572.867       3572.867       3572.867
| |-Node (0)
| | |Map gemm_16:
| | |          3567.709       3567.709       3567.709       3567.709
| |-Node (7)
| | |Tasklet 0_0_7:
| | |          0.000          0.000          0.000          0.030
| |-Node (9)
| | |Tasklet 0_0_9:
| | |          0.000 …
```
=> Include event names in `sdprof` reports

dace/codegen/compiler.py, dace/codegen/targets/fpga.py, dace/sdfg/sdfg.py, dace/transformation/dataflow/map_unroll.py, samples/fpga/gemm_systolic_vectorized.py, tests/fpga/intel_fpga_test.py, tests/fpga/map_unroll_processing_elements.py, tests/fpga/xilinx_test.py
Unroll maps with schedule `Unrolled` as part of the FPGA codegen in order to detect them as processing elements.
This is potentially fishy, since we are applying a transformation during code generation (!!) that modifies the SDFG. It is, however, a neat way of avoiding manually handling this in the FPGA codegen when detecting and generating modules.
=> Unroll PEs in FPGA Codegen

dace/codegen/targets/fpga.py
This fix tries to detect local buffers on an SDFG path, and, if this is the case, then the path should not be in a different kernel
=> FPGA Kernel detection fixes

dace/transformation/dataflow/map_unroll.py
At the moment all local transients will be returned, which leads to problems if there are any outside of the map which is unrolled.
=> Bugfix for map unroller

.github/workflows/python-package.yml, pytest.ini
To make sure we don't pick up any tests in other repositories.
=> Ignore external submodules when running pytest

dace/codegen/targets/fpga.py, dace/libraries/stencil/_common.py, dace/libraries/stencil/cpu.py, dace/libraries/stencil/intel_fpga.py, dace/libraries/stencil/stencil.py, dace/libraries/stencil/subscript_converter.py, dace/sdfg/replace.py, tests/library/stencil/stencil_node_test.py
Ported the Intel FPGA stencil node expansion from StencilFlow, adapted to be able to read from arrays instead of streams.
The streaming implementation is not yet verified to work, since the `StreamingMemory` transformation does not work with this expansion, due to the read happening in the nested SDFG.
=> Intel FPGA Stencil Node Expansion

dace/codegen/targets/fpga.py
There was a mixup between the nanoseconds reported by OpenCL and microseconds expected by the profiler.
=> Fix FPGA profiling units

dace/transformation/interstate/sdfg_nesting.py
Input edges with empty memlets inside a Map scope do not attach to connectors. This PR fixes an issue where Inline SDFG fails to apply due to trying to match a `None` connector to those edges.
=> Fix for InlineSDFG and empty input memlets

dace/sdfg/replace.py, tests/symbol_mapping_replace_test.py
When replacing a symbol in a nested SDFG, the symbol mapping is updated with the following code:
```python
for symname, sym_mapping in propval.items():
propval[symname] = symbolic.pystr_to_symbolic(sym_mapping).subs(symrepl)
```
`sym_mapping` is the original symbol from the nested SDFG's parent. This symbol may have been defined by the user, e.g., `sym = dace.symbol('sym', dtype=dace.float64)`. On the other hand, `symrepl` is a symbolic dictionary created with `pystr_to_symbolic`, which returns symbols with the default (integer) datatype. Please note, that `pystr_to_symbolic` will return the unmodified input if it is already a symbol. Therefore, any symbols that have been defined by with a non-default datatype will not be replaced by the above code. This PR fixes the issue in the …
=> Symbol Mapping Replacement Fix

dace/transformation/auto/auto_optimize.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/multistate_inline.py, tests/inlining_test.py
In the auto-optimizer, before applying LoopToMap to all levels of the SDFGs, we must split the interstate edges to all levels of the SDFG as well (not only the top-level SDFG). This PR also updates LoopToMap slightly to work with multi-state loop bodies that contain double-linked chains of nested loops. Furthermore, the PR changes the multi-state inline transformation to non-strict.
=> Split interstate edges of all SDFGs before LoopToMap

dace/transformation/dataflow/strip_mining.py, tests/numpy/linalg_test.py
Added support for proper range/image computation of indices with a negative multiplier on the tiled index.
NOTE: The whole thing should be rewritten at some point to interact with the propagation classes but still preserve the approximated ranges/images.
=> Descending range support in StripMining

dace/libraries/standard/nodes/gearbox.py, tests/fpga/memory_buffering_test.py
Also support converting between vectors of different sizes with a vector length that is a multiple length of each other, e.g., `vector(dace.float32, 16) <-> vectr(dace.float32, 4)`.
=> Data Width Conversion Upgrade

dace/frontend/python/newast.py, dace/sdfg/sdfg.py, dace/transformation/dataflow/__init__.py, dace/transformation/dataflow/redundant_array.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/state_fusion.py, tests/transformations/redundant_slices_test.py
This PR introduces the RedundantReadSlice and RedundantWriteSlice transformations. We define slices as DaCe Views of DaCe Arrays following the same semantics as NumPy Views generated by slicing NumPy Arrays with basic indexing. The new transformations are essentially simplified versions of RedundantArray and RedundantSecondArray with much stricter constraints. Furthermore, `SDFG.apply_strict_transformations` makes a first pass over the new transformations (only) in order to simplify the graph as much as possible before continuing with the other strict transformations.
=> Redundant Read/Write Slices

dace/frontend/python/newast.py, tests/numpy/copies_and_views_test.py
This PR generates data copies on self-assignments with partial overlap of the read and write subsets. Examples:
- `q[3 + j, 4 + i, 0:3] = q[3 - i + 1, 4 + j, 0:3]` will result in Array q -> View q_0 -> Array q
- `q[3 + j, 4 + i, 0:3] = q[3 - i + 1, 4 + j, 1:4]` will result in Array q -> View q_0 -> Transient q_0_0 -> Array q
=> Copy on self-assignment with partial overlap

dace/transformation/auto/auto_optimize.py, dace/transformation/interstate/sdfg_nesting.py
The LoopToMap transformation may create a nested SDFG for the loop-body that has input and output the whole range of each read or written array. Using the entire range of an array may prohibit further optimizations. This PR overcomes this issue by having the auto-optimizer use LoopToMap in conjunction with RefinedNestedAccess.
=> Refine nested access after loop2map

dace/frontend/python/newast.py, tests/python_frontend/nested_name_accesses_test.py
When accessing an outer-scope array in a nested context, we must squeeze its shape and access ranges to the smallest values that we can infer. To that end, we check whether the access ranges are dependent on symbols defined locally in the nested context. We use the ranges of the local symbols to infer the "squeezed" shape of the array's connector to the local context. However, we must also offset the access indices that are dependent on those local symbols, such as that accesses to the connector start from 0. This PR introduces such offsetting in the ProgramVisitor's `_add_access` methods.
=> Nested access offset fix

dace/frontend/python/newast.py, tests/python_frontend/augassign_wcr_test.py
Adds support for cases such as `A[2, 3, 1:4] += A[2:5, 1, 4]`, where WCR is not needed but is added due to the slicing of the RHS.
=> Unnecessary WCR fix

dace/codegen/targets/cpp.py, dace/codegen/targets/fpga.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/xilinx.py, tests/npbench/nussinov_test.py
Preprocessing pass for Xilinx: it goes over interstate edges and replaces names of the accessed arrays with their qualified ones (if any).
The nussinov polybench test trigger this behavior.
Partially solves #902
=> Xilinx preprocess interstate edges (take care of array name)

dace/codegen/targets/cpu.py, dace/codegen/targets/cuda.py, dace/codegen/targets/fpga.py, dace/data.py, dace/sdfg/sdfg.py, tests/sdfg/reference_test.py
Typed/shaped pointers that can be set at runtime. Necessary for supporting several challenging programs, while skirting around optimizing _some parts_ of them.
As opposed to Views, there are no special graph rules (e.g. edge node) for references, as once they are set, they can be used as normal access nodes. Aliasing rules do apply though and transformations (e.g., redundant array) can be amended at a later PR. Future PRs may eliminate trivial References via passes/transformations too.
It is not accessible from frontends at this point on purpose, as those constructs are highly discouraged.
=> Add support for Reference data descriptors

README.md, dace/config.py
Respect reversed priority order when trying to save a file: home directory first, then cwd, then operate with in-memory config using the default settings.
=> Container compatibility for config files

dace/frontend/python/astutils.py, dace/frontend/python/newast.py, dace/frontend/python/preprocessing.py, tests/python_frontend/callback_autodetect_test.py
=> Support callbacks with keyword arguments

dace/transformation/interstate/state_fusion.py, tests/control_flow_test.py, tests/transformations/state_fusion_test.py
Fixes issue #1005 
StateFusion must not happen if the assigned symbols in the states' common interstate edge are free symbols in any of the first state's input edges.
=> Fix for issue #1005

dace/cli/sdfv.py
When `filename` argument of SDFV is an int, start a `http.server` to serve the generated HTML and the dependencies.
This is really useful when interactively debugging sdfgs on a remote machine; you can just do `sdfg.view(8000)` (e.g. from within PDB), local-forward that port via SSH and then view the sdfg.
=> SDFV: Add web serving capability

dace/codegen/compiled_sdfg.py, dace/codegen/control_flow.py, dace/codegen/cppunparse.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/cuda.py, dace/codegen/targets/framecode.py, dace/frontend/python/parser.py, dace/frontend/python/preprocessing.py, dace/sdfg/graph.py, dace/sdfg/nodes.py, dace/sdfg/sdfg.py, dace/symbolic.py, dace/transformation/auto/auto_optimize.py, dace/transformation/interstate/move_loop_into_map.py, dace/transformation/interstate/multistate_inline.py, dace/transformation/passes/scalar_to_symbol.py, samples/fpga/gemv_fpga.py, tests/codegen/allocation_lifetime_test.py, tests/codegen/control_flow_detection_test.py, tests/codegen/nested_kernel_transient_test.py, tests/codegen/unparse_tasket_test.py, tests/compile_sdfg_test.py, tests/inlining_test.py, tests/passes/scalar_to_symbol_test.py, tests/python_frontend/global_folding_test.py, tests/transformations/move_loop_into_map_test.py
* Fix for general case is still pending semantics decision
=> Assortment of simple fixes

dace/frontend/python/parser.py
Context;  case of` ForwardRef("TYPE")` and `Union[ForwardRef('TYPE')", NoneType]`
Solution: evaluate the annotation to resolve true type
Drawback: Might resort to "compiletime" and also evaluating arbitrary code
=> Evaluate annotations w/ resolving their type

setup.py
This fixes installation for platforms that do not natively install the `scikit-build` or `cmake` pip packages, but have CMake installed.
=> Do not try to install CMake if it already exists

dace/codegen/instrumentation/__init__.py, dace/codegen/instrumentation/likwid.py, dace/codegen/instrumentation/report.py, dace/dtypes.py, dace/runtime/include/dace/perf/reporting.h, samples/instrumentation/matmul_likwid.py, tests/fpga/kernel_detection_test.py
PR for supporting LIKWID instrumentation in DaCe. The implementation is self-contained in the sense that it does not need to be wrapped by the *likwid-perfctr* tool.
The available groups (events + metrics) for each architecture can be found in likwid's groups folder, e.g. [Skylake](https://github.com/RRZE-HPC/likwid/tree/master/groups/skylake)
```bash
(transfer) ltruemper@davinci:~/Documents/repos/dace/samples/instrumentation$ OMP_NUM_THREADS=2 LIKWID_EVENTS="FLOPS_SP" python matmul_likwid.py
Instrumentation report
SDFG Hash: dc18bdc7f2fb1cff5893ea15c59e78e72d229721826faacc3f6b1e81ae522cd5
---------------------------------------------------------------------------
Element        Runtime (ms)
Min            Mean           Median         Max …
```
=> Native LIKWID Instrumentation

dace/data.py, dace/dtypes.py, tests/array_interface_test.py
This PR implements support for objects implementing the `__array_interface__` similar to the already supported `__cuda_array_interface__`
=> Support for `__array_interface__`

dace/frontend/python/newast.py, dace/frontend/python/replacements.py, tests/numpy/assignment_test.py, tests/numpy/binop_broadcasting_test.py
Previously, broadcasting with symbolic shapes would not do symbolic equality checking when checking broadcasting. For example, the following arrays would not broadcast together:
```
A: shape [N,]
B: shape [N * (j + 1) - N * j]
```
I'm pretty sure that there are many other cases where this is being done incorrectly, but this helps for my use case for now.
=> Add proper symbolic equality checks for broadcasting

dace/transformation/interstate/sdfg_nesting.py, tests/inlining_test.py
Previously, InlineSDFG would fail to correctly determine the viewed array name when inlining an SDFG inside a scope.
=> Fix InlineSDFG behavior in scopes with views

dace/data.py
Previously the storage of torch tensors was ignored. Also fixes a regression introduced in #1071.
=> Set storage type for torch tensors when creating data descriptors

dace/codegen/targets/cpp.py, dace/codegen/targets/framecode.py, dace/sdfg/sdfg.py, tests/constant_array_test.py
Previously, the code generator would not be aware when an input to a NestedSDFG is constant, causing compiler errors related to ``const``.
=> Support constants in SDFG.data, Propagate constants into NestedSDFGs.

dace/transformation/dataflow/otf_map_fusion.py, tests/transformations/otf_map_fusion_test.py
So far, OTFMapFusion was only appliable in cases where the map parameters of both maps did match. I generalized the implementation by solving the equation systems of the memlets, i.e., 
second map reads tmp[i, j]
first map writes tmp[k, l]
we know: i -> k, j -> l
I am also renaming the map parameters temporarily in the equations so that the two maps can have the same parameters but in permuted order:
second map reads tmp[i, j]
first map writes tmp[j, i]
j -> i, i -> j
Update:
- I added support for tree-like cases
- Fixed a frequently occurring problem where the in_connector name was already taken
=> OTFMapFusion re-implemented

dace/dtypes.py
This was caught by the daceml test suite
=> Fix typo in schedule inference

dace/config_schema.yml, dace/frontend/python/newast.py, dace/sdfg/utils.py, dace/transformation/passes/constant_propagation.py, tests/python_frontend/augassign_wcr_test.py, tests/python_frontend/loops_test.py
The PR addresses two issues:
The frontend has a feature where the write-subsets of augmented assignments appearing inside Maps are checked for dependency on the Map parameters. According to the results of this check, the frontend will avoid using WCR and instead generate a subgraph where the write-data appear explicitly as read-data too. However, this feature will not work correctly when a Map has multiple writes to the same dimension of a data container, with index expressions that create write-conflicts (see `tests.python_frontend.augassign_wcr_test.augassign_wcr4`). We cannot rectify the issue within the bounds of the frontend's current design, which is not to look ahead for the following statements in the code. Instead of removing the feature altogether, which may have undesired …
=> Frontend fixes

dace/sdfg/state.py, dace/transformation/interstate/sdfg_nesting.py
- When adding a NestedSDFG and there are missing symbols, check if they are defined in the parent. If yes, add them to the symbol mapping.
- RefineNestedAccess resets the loop ranges in the candidate nested SDFGState because they might have been altered from another transformation (is this valid any longer?). However, the loop ranges of all the states must be reset due to how `_annotate_loop_ranges` works (if the guard is correctly annotated, it skips annotating the body).
=> Fix SDFGState.add_nested_sdfg and RefineNestedAccess transformation

dace/data.py, dace/frontend/python/interface.py, dace/frontend/python/newast.py, dace/frontend/python/preprocessing.py, tests/python_frontend/device_annotations_test.py
This enables parsing statements like
```python
for i in dace.map[0:N] @ ScheduleType.GPU_Device
...
```
And:
```python
def add(X: dace.float32[32] @ StorageType.GPU_Global):
...
```
(Inspired by https://exo-lang.dev)
=> Frontend: add syntactic sugar for schedule and storage types.

dace/codegen/cppunparse.py, dace/dtypes.py, dace/frontend/common/einsum.py, dace/frontend/python/astutils.py, dace/frontend/python/cached_program.py, dace/frontend/python/common.py, dace/frontend/python/newast.py, dace/frontend/python/parser.py, dace/frontend/python/preprocessing.py, dace/frontend/python/replacements.py, setup.py, tests/python_frontend/string_test.py
Before this PR, there was effectively no difference between a string and an array name.
Fixes #1072
=> Explicit support for string literals in Python frontend

tests/transformations/local_storage_test.py
When calling to_json on LocalStorage transformations, I saw that it did not add the chosen array to the "array" field. I first thought it was a bug and wrote some tests to check but then realized this is by intention when no "array" was provided. Anyway, I think it's good to add the additional tests I wrote
=> Additional local storage tests

dace/frontend/python/common.py, dace/frontend/python/interface.py, dace/frontend/python/newast.py, dace/frontend/python/preprocessing.py, tests/python_frontend/assignment_statements_test.py, tests/python_frontend/method_test.py, tests/python_frontend/string_test.py
=> Frontend errors and behavior fix

dace/codegen/compiled_sdfg.py, dace/config_schema.yml, dace/data.py, dace/dtypes.py, dace/frontend/python/common.py, dace/frontend/python/interface.py, dace/frontend/python/newast.py, dace/frontend/python/preprocessing.py, dace/runtime/include/dace/pyinterop.h, tests/python_frontend/assignment_statements_test.py, tests/python_frontend/callback_autodetect_test.py, tests/python_frontend/callee_autodetect_test.py, tests/python_frontend/method_test.py, tests/python_frontend/string_test.py
Callbacks can return arbitrary pyobjects, which are only reusable in other callbacks.
Also includes bugfixes for callbacks and return values, as well as tests.
=> PyObject Callbacks

dace/transformation/dataflow/otf_map_fusion.py, tests/transformations/otf_map_fusion_test.py
This PR extends and fixes OTFMapFusion
- Fusion of maps with WCR in second map
- Fusion of maps with NestedSDFGs
- Renaming of symbols to avoid symbol collision of map parameters
- Renaming of symbols in NestedSDFG to avoid collision with map parameters
=> OTFMapFusion: Support for WCR, nested maps & connector renaming fixed

dace/frontend/python/preprocessing.py
Fixes an issue where symbolic arguments to methods becoming callbacks are considered constants. This leads to a program crash because DaCe symbols cannot be used in (pure) Python code.
=> Fix for symbolic arguments in callbacks

dace/sdfg/propagation.py, tests/memlet_propagation_test.py
=> Fix memlet propagation out of nested SDFGs

dace/runtime/include/dace/cuda/cudacommon.cuh
The `syncdebug` option in DaCe allows to check for CUDA errors after each maps. In a context of a large codebase with plenty of logs some of those errors are easy to miss since runtime keeps going. In the case of a 701 (where the kernel silently doesn't run) this can lead to numerical instability way later. Hard to debug for non-power user.
This introduces a simple `throw;` in the macro which triggers a SIGABRT right after the issue, creating a much more clear debug situation.
(co-authored with Tal Ben-Nun)
=> throw in DACE_CUDA_CHECK to stop runtime on CUDA error

AUTHORS, dace/libraries/standard/nodes/reduce.py, dace/libraries/standard/reduction_planner.py, dace/transformation/auto/auto_optimize.py
This PR adds very little code to `auto_optimize.py`. The added code ensures that the `GPUAutoExpansion` gets used for reduce nodes, when `auto_optimize` is used to optimize the produced SDFG.
Before, it would always choose `CUDA (device)` even though the `GPUAuto` expansion is higher in the `implementation_prio`.
=> auto_optimize now properly chooses GPUAuto expansion for reduce nodes

dace/transformation/interstate/loop_to_map.py, tests/transformations/loop_to_map_test.py
When applying LoopToMap to a for-loop whose body is nested to complete the transformation, any transient data used exclusively inside the body become transient data of the nested SDFG, i.e., thread-local variables. Although this is technically always correct, it could be more efficient in the case of Arrays that can be partitioned to disjoint subsets per loop iteration. This PR adds to LoopToMap functionality to detect and keep such data shared among all Map iterations.
=> LoopToMap detects shared transients

dace/transformation/helpers.py, tests/inlining_test.py
This PR includes fixes done in `unsqueeze_memlet` done during the development of the Fortran frontend.
=> `unsqueeze_memlet` fixes

AUTHORS, dace/frontend/python/parser.py
This is pr tries to fix the issue #1175, which suggests we can warn users when calling to_sdfg on a function that shouldn't be reparsed.
_This issues has been discussed before in #1204._
Add a warning message in the method `to_sdfg` under `dace/frontend/python/parser.py`.
=> Add warning when user calls to_sdfg on a function that shouldn't be reparsed

dace/frontend/python/newast.py, tests/numpy/subarray_in_nested_call_test.py, tests/python_frontend/indirections_test.py
In the Python frontend, if an indirect access to the same range appears more than once, the second time onwards will not create a slice access. This PR fixes it to always create a slice as necessary.
=> Fix internal subscript access if already existed

dace/transformation/interstate/gpu_transform_sdfg.py, tests/transformations/gpu_transform_test.py
This PR solves an issue with GPUTransform where copying an array from GPU global memory back to the host overwrites values that weren't updated in the kernel.
=> Fix-gpu-transform-copy-out

dace/codegen/instrumentation/likwid.py, dace/sdfg/analysis/cutout.py, dace/transformation/dataflow/tiling.py
Changes:
- Increased the maximum number of events allowed in LIKWID GPU instrumentation.
- Allow for trivial tiling in MapTiling, which facilitates transfer tuning to different input sizes.
- Switched iteration style in Cutout API. It should be semantically identical code, but somehow fixes a bug in the API. This needs to be investigated later in detail.
=> Tuning Compatibility Fixes

dace/sdfg/sdfg.py, tests/sdfg/free_symbols_test.py, tests/transformations/state_elimination_test.py
This PR attempts to fix a long standing issue with the computation of an SDFG's free symbols, especially symbols that are used before being assigned. The PR introduces a new algorithm for computingg an InterstateEdge's free symbbols, which is subsequently used to correctly compute the used-before-assigned SDFG free symbols.
=> Fix-interstate-free-symbols

.github/workflows/fpga-ci.yml, .github/workflows/general-ci.yml, .github/workflows/gpu-ci.yml, .github/workflows/heterogeneous-ci.yml, dace/frontend/python/newast.py, tests/python_frontend/nested_name_accesses_test.py
In the Python frontend, when accessing an array from a higher-level scope, we try to "squeeze" the access to begin from index 0 while propagating the correct offset to the edge connecting the outer data to the nested scope (NestedSDFG). To achieve this, any access utilizing a symbol `k` that is local to the nested scope with an access method `f(k)` is altered to `f(k) - f(min(range(k))` so that it starts from index 0, while the offset `f(min(range(k))` is propagated to the outer edge.
However, issues arise when the symbol `k` range depends on other symbols local to the nested scope. In those cases, the symbols have to be altered/replaced recursively so that no local symbol remains in the offset; otherwise, it is impossible to propagate it to the outer edge, which then starts from index 0, …
=> Fix nested access with nested symbol dependency

dace/frontend/python/interface.py, dace/frontend/python/preprocessing.py, tests/python_frontend/inline_preprocessing_test.py
This PR adds the `dace.inline` function to the Python frontend. The preprocessor will call the internal expression at compile-time and replace the value with the results.
=> Inline preprocessor command

dace/frontend/python/newast.py, tests/python_frontend/indirection_in_map_test.py
For programs like CSR times CSR matrix:
```python
@dace.program
def spmspm_csr_csr(A2_pos: dace.int32[M + 1], A2_crd: dace.int32[nnz_A], A_val: dace.float64[nnz_A],
B2_pos: dace.int32[N + 1], B2_crd: dace.int32[nnz_B], B_val: dace.float64[nnz_B],
C: dace.float64[M, K]):
for i in dace.map[0:M]:
for pj in dace.map[A2_pos[i]:A2_pos[i + 1]]:
for pk in dace.map[B2_pos[A2_crd[pj]]:B2_pos[A2_crd[pj] + 1]]:
C[i, B2_crd[pk]] += A_val[pj] * B_val[pk]
```
`to_sdfg()` fails to parse `B2_pos[A2_crd[pj]]`.
Fixed the corner case in `_parse_map_inputs` where `candidate` can be either `Scalar` or  `Array` of shape (1,).
=> Fix map indirection

dace/transformation/helpers.py, dace/transformation/interstate/loop_to_map.py, tests/transformations/loop_to_map_test.py
This PR added a helper method for redirecting a Map's internal write to an output Access node. It further amens LoopToMap to make use of this method.
=> Make-intermediate-map-writes-external

dace/codegen/targets/cpp.py, tests/codegen/unparse_tasklet_test.py
This PR addresses the issue of implicit casting in (floating point) pow operations being stripped from the generated code due to an optimization concerning integer pow operations.
=> Fix for #1220

AUTHORS, doc/setup/installation.rst
On some systems with OpenBLAS installed, libblas.so and liblapacke.so may need to be created manually as symlinks to libopenblas.so.
=> Doc: Installation: Add OpenBLAS symlink tip

dace/transformation/dataflow/map_interchange.py, tests/transformations/map_interchange_test.py
This PR fixes an issue with MapInterchange where accesses to Memlet paths go out of bounds because the algorithm expects a next (previous) edge that doesn't exist. This issue occurs with edges that carry dynamic Map inputs, i.e., the Memlet path stops at a MapEntry and not a CodeNode.
=> Fix MapInterchange for Maps with dynamic inputs

dace/codegen/targets/cuda.py, tests/dynamic_tb_map_cudatest.py
This PR addresses the following issues:
=> Assortment of fixes for dynamic Maps on GPU (dynamic thread blocks)

dace/frontend/python/newast.py, tests/python_frontend/fields_and_global_arrays_test.py
This PR alters how closure arrays are added to (nested) SDFGs. Instead of matching (and updating) by name, potentially causing ambiguities, it uses the actual array objects. The new algorithm handles the following cases:
- Closure array has not been added yet (see `ProgramVIsitor.nested_closure_arrays`):
- Add to the SDFG with, if needed, a new name.
- Closure array has already been added:
- Array doesn't exist in the SDFG, i.e., it is in a nested scope:
- Add it to the SDFG with the same name.
- Array exists in the SDFG:
- Don't add it to the SDFG
In all the above cases, the array should end up in the (nested) SDFG's arguments with the appropriate name.
=> Closure array handling update

.github/workflows/general-ci.yml, dace/frontend/python/newast.py, dace/sdfg/utils.py, dace/symbolic.py, tests/inlining_test.py, tests/npbench/polybench/correlation_test.py
Fixes for compatibility with SymPy 1.12.
The main issue concerns symbolic substitution. In SymPy 1.12, the new values are sympified with `strict=True,` which allows the sympification of only scalar values (no `None` values, `Callable`s. `Iterable`s, and strings). This PR addressed the issue in the following manner:
- `None` values, `Callable`s, and `Iterable`s are filtered out from the replacement dictionaries since it is unlikely that their corresponding old values need to be replaced.
- Strings are first converted to `sympy.symbol`s since they should be symbol names.
=> SymPy 1.12

dace/codegen/instrumentation/likwid.py
This PR adds an environment definition for LIKWID. 
Although Likwid does not define a cmake target, the environment enables adding search paths for headers and libraries conveniently, e.g. CONDA_PREFIX.
=> Added LIKWID environment

dace/codegen/targets/snitch.py, dace/libraries/blas/nodes/dot.py, dace/libraries/standard/nodes/reduce.py, dace/transformation/subgraph/composite.py
- Some import paths were not compatible with python3.6
- The g++ compiler on MacOS installed through Homebrew seems to rely on MacOS SDK built with clang, for which __unused is a reserved word (an attribute), therefore variables cannot be named __unused.
=> Fix compile errors

dace/codegen/compiled_sdfg.py, dace/codegen/targets/fpga.py, dace/codegen/targets/framecode.py, dace/dtypes.py, dace/libraries/blas/nodes/gemm.py, dace/libraries/blas/nodes/matmul.py, dace/sdfg/infer_types.py, dace/sdfg/utils.py, dace/transformation/auto/auto_optimize.py, dace/transformation/interstate/multistate_inline.py, dace/transformation/interstate/sdfg_nesting.py, dace/transformation/subgraph/gpu_persistent_fusion.py, dace/transformation/transformation.py, tests/parse_state_struct_test.py, tests/sdfg/schedule_inference_test.py
This is a lighter version of #1241 without the entire SDFG device revamp. This PR fixes #1185 by inferring schedule types of maps based on the surrounding storage types (skipping scalar values). As opposed to #1241, this PR does not remove the `GPU_Default` schedule.
Comment for changelog @phschaad:
The schedule type of a scope (e.g., a Map) is now also determined by the surrounding storage. If the surrounding storage is ambiguous, dace will fail with a nice exception. This means that codes such as the one below:
```python
@dace.program
def add(a: dace.float32[10, 10] @ dace.StorageType.GPU_Global, 
b: dace.float32[10, 10] @ dace.StorageType.GPU_Global):
return a + b @ b
```
will now automatically run the `+` and `@` operators on the GPU.
=> Determine schedule type based on surrounding storage types

dace/frontend/python/newast.py, tests/python_frontend/nested_name_accesses_test.py
Fixes a bug that renders subscripted accesses to data defined inside a nested scope (e.g., a Map) to full-range accesses to the same data.
=> Fix writes to nested definitions

dace/sdfg/sdfg.py
=> Make SDFG.name a proper property

AUTHORS, dace/codegen/targets/cuda.py
I've encountered an error on ROCm systems where the target ID has "gfx" set twice (e.g., "gfxgfx906" instead of "gfx906"), which causes compile-time issues. I have fixed this issue by adding a check if "gfx" is already part of the architecture, and only prepending "gfx" if it isn't.
=> Fix ROCm issue where target ID is set to gfxgfx***

dace/frontend/python/newast.py, tests/numpy/attribute_test.py
The PR adds a new SDFGState when handling Python AST Attribute nodes implemented through a replacement method. This ensures that no dependencies are violated in cases where the attribute depends on the output(s) of the last SDFGState.
=> New State for Attribute Replacements

dace/codegen/codegen.py, dace/codegen/common.py, dace/codegen/compiled_sdfg.py, dace/codegen/dispatcher.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/cuda.py, dace/codegen/targets/fpga.py, dace/codegen/targets/framecode.py, dace/codegen/targets/snitch.py, dace/dtypes.py, dace/sdfg/sdfg.py, dace/sdfg/validation.py, dace/transformation/interstate/sdfg_nesting.py, dace/transformation/passes/dead_dataflow_elimination.py, dace/transformation/passes/scalar_to_symbol.py, tests/codegen/external_memory_test.py
This PR is important for interoperability with other frameworks, whose memory management is external. It provides an allocation lifetime and generates two functions to get required sizes and set pointers externally.
=> Externally-managed memory lifetime

dace/frontend/common/distr.py, dace/libraries/mpi/nodes/__init__.py, dace/libraries/mpi/nodes/alltoall.py, tests/library/mpi/mpi4py_test.py, tests/library/mpi/mpi_allgather_test.py, tests/library/mpi/mpi_alltoall_test.py, tests/library/mpi/mpi_isend_irecv_test.py, tests/library/mpi/mpi_send_recv_test.py
Added mpi4py send/recv support and alltoall library node
Added replacements and unit tests for mpi4py.MPI.COMM_WORLD.Send and mpi4py.MPI.COMM_WORLD.Recv.
Implemented the library node and unit test for the alltoall collective.
=> Added mpi4py send/recv support and alltoall library node

dace/codegen/targets/cuda.py, dace/runtime/include/dace/cuda/cudacommon.cuh, dace/transformation/auto/auto_optimize.py
Two minor fixes in this PR:
* Fix for double-free of external streams if `__dace_gpu_set_stream` was called
* Fix auto-optimize removing `External` lifetimes
=> External interaction fixes

dace/transformation/interstate/sdfg_nesting.py, tests/transformations/refine_nested_access_test.py
This PR adds InterstateEdge support to RefinedNestedAccess, i.e., data accesses appearing in InterstateEdges will be recorded to the candidate registries.
=> Adds InterstateEdge check to RefinedNestedAccess

dace/frontend/python/newast.py, dace/frontend/python/replacements.py, tests/python_frontend/conditionals_test.py
Fixes the case where the result of visiting a condition's/while's test is a list/tuple of size 1 and isn't unpacked correctly. It also adds a special case when converting data to bool because we do not/cannot define `dace::bool`.
=> Fix for #1308

dace/sdfg/validation.py, dace/transformation/dataflow/map_fusion.py, tests/transformations/mapfusion_test.py
This PR:
- Adds a validation check for edges/Memlet paths and NestedSDFGs; if a NestedSDFG is src/dst of a Memlet path, then the dst/src must be an AccessNode.
- Amends MapFusion to create new intermediate data, even when the access is Scalar, when connecting one or more NestedSDFGs.
=> Fix MapFusion with NestedSDFGs

dace/sdfg/utils.py, dace/transformation/subgraph/subgraph_fusion.py, tests/transformations/subgraph_fusion/intermediate_mimo_test.py
The PR fixes removal of intermediate nodes to non-local data in SubgraphFusion, taking into account dependencies among those nodes.
=> Fixes Intemediate Node Removal in SubgraphFusion

dace/sdfg/graph.py, dace/sdfg/sdfg.py, tests/graph_test.py
The method `dace.sdfg.graph.Graph.dfs_edges` avoids cycles by keeping track of visited nodes (SDFGStates). While iterating over the out-edges of a node, if the destination has already been visited, it skips it. However, the edge should still be yielded, otherwise, not all of them will be returned. For example, the former algorithm skips the back-edge leading from the body of a for-loop to its guard.
UPDATE: To fix a (newly) failing test, this PR also amends `InterstateEdge.new_symbols` to return only newly defined symbols. For example, if the InterstateEdge consists of the assignment `i = i + 1`, `InterstateEdge.new_symbols` **will not** return `i` any longer. The method uses the same algorithm as `InterstateEdge.free_symbols` to infer which symbols are actually defined.
=> Fix for DFS edges method

dace/frontend/python/newast.py
This PR refactors the frontend's visitors responsible for access to variables/data (`visit_Name`, `visit_Subscript`, etc.). The intent is to unify handling of read and write accesses in the assignment visitors to simplify supporting Structures.
=> Refactoring Frontend's Variable-Access Visitors

dace/frontend/python/replacements.py, dace/libraries/blas/nodes/batched_matmul.py, dace/libraries/blas/nodes/gemm.py, dace/libraries/blas/nodes/matmul.py, dace/symbolic.py, tests/library/gemm_test.py, tests/numpy/matrix_multiplication_test.py
This PR introduces a new equality-check method, mainly aimed at dimension/mode length checks. The new method returns `True` if the two arguments are equal, `False` if they are unequal, and `None` if the result cannot be determined. The PR also introduces example usages in matrix-multiplication-related functionality, utilizing the method to print warnings instead of throwing errors when matrix multiplication could be valid depending on the values symbols take.
=> Relaxed Shape/Size Equality Checks

dace/codegen/targets/cuda.py, dace/properties.py, dace/transformation/passes/prune_symbols.py, dace/transformation/subgraph/gpu_persistent_fusion.py, tests/codegen/gpu_scalar_execution_context_test.py, tests/persistent_fusion_cudatest.py
=> Fixes for persistent schedule and GPUPersistentFusion transformation

AUTHORS, dace/sdfg/state.py, dace/transformation/interstate/sdfg_nesting.py, tests/sdfg/state_test.py
`read_and_write_sets()` filters out reads which are written directly before to the same AccessNode. Will only work if the read and write memlet go to the same AccessNode
=> state.read_and_write_sets() ignore reads directly after writes

dace/frontend/python/newast.py, dace/transformation/passes/array_elimination.py
This PR addresses the following:
=> Pace Fixes 0

samples/codegen/tensor_cores.py
After messing with the tensor core example some, myself and @tbennun noticed some issues with the sample. This PR fixes a few issues.
1. The storage types (e.g., `Accumulator`, `TensorCore_*`) have been added to `defined_vars`. In some cases not demonstrated in `hgemm`, the codegen generates improper passes to functions. By setting the type to `DefinedType.Stream`, we ensure that the WMMA fragments are always passed as an object reference.
2. The frontend is greatly redone and simplified, changing the use of `@replaces` to simple `dace.tasklet`s. As with 1, certain situations not exposed with `hgemm` showed that memlets are not always properly generated with the `frag_fill` and `wmma` functions. Changing their implementation to `dace.tasklet` ensures that memlets are now properly …
=> Fix some underlying issues with tensor core sample

dace/cli/daceprof.py, dace/codegen/instrumentation/likwid.py, dace/codegen/instrumentation/papi.py, dace/codegen/targets/cpu.py, dace/dtypes.py, dace/sdfg/nodes.py, dace/transformation/interstate/sdfg_nesting.py, tests/openmp_test.py
This PR adds the ability to generate per-thread code without a for loop, using `#pragma omp parallel`.
It inherits all the OpenMP properties that the parallel for has (e.g., schedule, number of threads), and internal OpenMP loops detect that they are nested in a parallel region.
It also allows the user to obtain the current thread ID (i.e., the map parameter) and the total number of runtime threads via the reserved `__omp_num_threads` symbol.
=> Add `CPU_Persistent` map schedule (OpenMP parallel regions)

dace/frontend/fortran/fortran_parser.py, tests/fortran/array_test.py
Fixes error with memlet indices. Parser made implicit assumption about position of index a loop iterations over. Also added a testcase.
=> Fortran fix memlet indices

dace/codegen/compiled_sdfg.py, dace/codegen/dispatcher.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/framecode.py, dace/data.py, dace/dtypes.py, dace/frontend/python/replacements.py, dace/properties.py, dace/sdfg/sdfg.py, dace/sdfg/utils.py, dace/sdfg/validation.py, tests/sdfg/data/struct_array_test.py, tests/sdfg/data/structure_test.py
This PR implements the Nested Data proposal only for the SDFG IR (no frontend support).
=> Nested Data Proposal (SDFG only)

dace/sdfg/propagation.py, tests/python_frontend/argument_test.py
Memlet propagation had a branch bug (`elif` vs. `if`) where if the memlet is dynamic, defined symbols were no longer checked. This simple fix adds a test and corrects this behavior.
=> Fix dynamic memlet propagation condition

dace/frontend/fortran/ast_components.py, requirements.txt, setup.py
This PR updates the core Fortran dependency and makes our code compatible with the restructurization of this third-party package. Should fix failing tests in #1370 
cc: @tbennun @acalotoiu
=> Update fparser to 0.1.3

dace/transformation/passes/analysis.py
The current algorithm in networkx is suboptimal. With this change, I noticed a 55x speedup in computing state reachability on realistic programs.
=> Speed up StateReachability pass for large state machines

tests/numpy/ufunc_support_test.py
In some specific random seeds, the following error occurs:
```
tests/numpy/ufunc_support_test.py:130: in test_ufunc_add_where
assert (not np.array_equal((A + B)[np.logical_not(W)], C[np.logical_not(W)]))
E   assert not True
E    +  where True = <function array_equal at 0x7f64de13d730>(array([], dtype=int32), array([], dtype=int32))
E    +    where <function array_equal at 0x7f64de13d730> = np.array_equal
```
This PR patches it by freezing the random seed.
=> Fix transient bug in test with `array_equal` of empty arrays

dace/codegen/control_flow.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/tools/type_inference.py, dace/symbolic.py, tests/sdfg/data/structure_test.py
I do not know how to make tests for that.
=> Support attributes in symbolic expressions

test_all.sh
Some versions of bash (which is the only thing the shebang asks for) do not support |&, on the other hand 2>&1 does the same thing and is widely supported.
=> replace |& which is not widely supported

dace/codegen/targets/rtl.py, samples/fpga/rtl/add_fortytwo.py, samples/fpga/rtl/axpy.py, samples/fpga/rtl/axpy_double_pump.py, samples/fpga/rtl/fladd.py, samples/fpga/rtl/pipeline.py, samples/fpga/rtl/rtl_multi_tasklet.py, samples/fpga/rtl/rtl_tasklet_parameter.py, samples/fpga/rtl/rtl_tasklet_pipeline.py, samples/fpga/rtl/rtl_tasklet_scalar.py, samples/fpga/rtl/rtl_tasklet_vector.py, tests/rtl/hardware_test.py, tests/rtl/simulation_test.py
The issue in #1383 uncovered flaws in the RTL samples: 
1. Unsupported RTL configurations not failing gracefully. 
The specific error arose when an RTL tasklet tried to access a stream during simulation mode, which is currently not supported in simulation mode, as the produced Verilator code does not mimick actual behaviour, resulting in a deadlock. Current "fix" is to emit this shortcoming as a comment in the resulting code. It should not always fail (hence the emission to a comment), since the RTL code generator is partially used by the Xilinx code generator, leading to said faulty code to be omitted anyways; at least for the samples/tests that reach this point.
2. The samples (at least not all of them) did not set the required DaCe configuration entries. 
Some of the samples did …
=> RTL codegen "line" error

dace/transformation/auto/auto_optimize.py
A standard workflow when transforming GPUs for GPU execution involves changing the storage of non-transient data to GPU global memory so that they are read/written directly from/to the device. Due to changes to SDFG validation, this workflow frequently fails because changing the storage (temporarily) invalidates reads and writes in InterstateEdges. This PR addresses the issue in the case of auto-optimization by adding an option to change the storage just before applying GPUTransformation.
=> Option for utilizing GPU global memory

dace/data.py, tests/sdfg/data/tensor_test.py
Format abstraction is based on [https://doi.org/10.1145/3276493].
It adds a new `Tensor` data descriptor as subclass of `Structure`, which
automatically has the necessary fields for the relevant indices.
The following index types are currently supported:
- Dense 
- Compressed (stores coordinates in segmented array akin to CSR)
- Singelton (stores one coordinate for every parent coordinate; used in COO)
- Range (computes coordinates based in current and parent dimension sizes + offset from parent)
- Offset (computes coordinates based on offset from parent coordinate)
=> Add tensor storage format abstraction

tests/sdfg/data/tensor_test.py
I left a save statement in one of the tests, which was just for debugging purposes. This creates the file `tests/tensor.json` every time the tests are run, which is a bit messy. This PR removes that.
=> Remove erroneous file creation in test

dace/cli/sdfv.py
Test system Mac OS
This small modification makes sure that in both modes (interactive & debug) the `sdfg.view()` will open the graph in the VS Code env (if present) and not in the available browser.
The `VSCODE_IPC_HOOK_CLI` env var is present in an interactive session from the VS Code termninal, but it is not present in the debug console. In the debugging mode, it is the `VSCODE_IPC_HOOK` env var which is present.
=> Fix for VS Code debug console: view opens sdfg in VS Code and not in browser

dace/codegen/compiled_sdfg.py, dace/codegen/instrumentation/data/data_dump.py, dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/codegen/targets/cuda.py, dace/codegen/targets/fpga.py, dace/codegen/targets/framecode.py, dace/codegen/targets/intel_fpga.py, dace/codegen/targets/mpi.py, dace/codegen/targets/xilinx.py, dace/config_schema.yml
This PR addresses issue  #1396, by modifying the way how the name of the state struct is created.
=> Better mangeling of the state struct in the code generator

dace/transformation/auto/auto_optimize.py
The `dict` that was storing all the symbols, `known_symbols`, was emptied just after its creation. The efect was that the specialization never took effect.
=> Symbol specialization in `auto_optimizer()` never took effect.

dace/sdfg/analysis/schedule_tree/sdfg_to_tree.py
If a data container appears as part of `read_symbols` (i.e., as the array, for `x is not None`), do not replace it with a memlet.
=> Fix schedule tree conversion for use of arrays in conditions

dace/sdfg/utils.py, tests/sdfg/validation/nested_sdfg_test.py
Adds utility-method support for the case of an in-out nested SDFG connector that is out-only at outer SDFG scopes.
=> In-out connector's global source when connector becomes out-only at outer SDFG scopes.

dace/codegen/codegen.py, dace/codegen/targets/cpu.py, dace/config_schema.yml, dace/properties.py, dace/sdfg/nodes.py, dace/sdfg/sdfg.py, dace/sdfg/state.py, dace/serialize.py, dace/transformation/transformation.py, tests/openmp_test.py, tests/transformations/local_storage_test.py
Added a configuration entry (enabled by default) that serializes only the modified fields in an SDFG. This leads to a reduction in size.
Merging this PR is contingent on updating the SDFG renderer to use the defaults/metadata for properties.
=> Do not serialize non-default fields by default

dace/config_schema.yml
This is in preparation of the `0.15.1` release to avoid introducing potentially breaking changes.
=> Changed default of serialize_all_fields to True

dace/memlet.py, dace/transformation/passes/analysis.py, tests/passes/access_ranges_test.py, tests/sdfg/reference_test.py
Adds two analysis passes to help with analyzing data access sets: access ranges and Reference sources. To enable constructing sets of memlets, this PR also reintroduces data descriptor names to memlet hashes.
=> Analysis passes for access range analysis

dace/codegen/targets/cpp.py, dace/codegen/targets/cpu.py, dace/sdfg/analysis/schedule_tree/sdfg_to_tree.py, dace/sdfg/analysis/schedule_tree/treenodes.py, dace/sdfg/validation.py, dace/transformation/passes/dead_dataflow_elimination.py, dace/transformation/passes/reference_reduction.py, dace/transformation/passes/simplify.py, tests/sdfg/reference_test.py
Implements a reference-to-view pass (converting references to views if they are only set to one particular subset). Also improves the simplify pipeline in the presence of Reference data descriptors and adds multiple tests that use references.
=> Reference-to-View pass and comprehensive reference test suite

dace/transformation/passes/reference_reduction.py, tests/sdfg/reference_test.py
Adds a scoped test that completes coverage for the reference-to-view pass, leading to fixes of issues in the uncovered code.
=> Complete coverage for reference-to-view pass

dace/codegen/cppunparse.py, dace/dtypes.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/libraries/blas/nodes/gemm.py, dace/libraries/sparse/nodes/csrmm.py, dace/libraries/sparse/nodes/csrmv.py, dace/sdfg/sdfg.py, dace/serialize.py, dace/symbolic.py
Prior to this PR, `dtype_to_typeclass` was evaluated at import time. This means that the configuration entry `default_data_types` could not be modified after importing dace in a meaningful way.
=> Evaluate dtype_to_typeclass at use time

dace/codegen/compiled_sdfg.py, dace/data.py, dace/dtypes.py, dace/libraries/standard/nodes/reduce.py, dace/libraries/standard/nodes/ttranspose.py, dace/runtime/include/dace/reduction.h
CuPy with AMD HIP does not support `__cuda_array_interface__`. This PR adds special cases to support CuPy with HIP.
The PR also fixes the reduce node's GPUAuto schedule with respect to warp size.
=> CuPy fixes and special cases for HIP

dace/codegen/dispatcher.py, dace/codegen/targets/cpu.py, dace/codegen/targets/framecode.py, dace/data.py, dace/sdfg/analysis/schedule_tree/sdfg_to_tree.py, dace/sdfg/sdfg.py, dace/sdfg/utils.py, dace/transformation/dataflow/redundant_array.py, dace/transformation/passes/reference_reduction.py, tests/sdfg/data/container_array_test.py, tests/transformations/redundant_slices_test.py
This PR refactors the notion of views to a `View` interface, and provides views to arrays, structures, and container arrays. It also adds a syntactic-sugar/helper API to define a view of an existing data descriptor. Depends on merging #1504
=> Generalize container views

dace/sdfg/validation.py
It was not considered that an empty memlet has `data` equal to `None`. However, empty Memlets should not be considered as duplicated data as they do not move data.
=> Fixed an issue in the Memlet duplication verification.

dace/sdfg/graph.py
The function ignored their `node` argument, thus they always returned all edges.
=> Fixed the `{in,out}_edges()` function of the `DiGraph` class.

dace/transformation/dataflow/map_expansion.py, tests/transformations/map_expansion_test.py
Before the transformation ignored the tiling parameter of the range, this was fixed. The transformation is now also able to limit the expansion. Thus it is possible to only expand the first k dimensions, the remaining dimensions will be kept in a multi dimensional map.
This is a feature that will be need in GT4Py.
=> Updated and fixed the MapExpansion transformation.

dace/transformation/dataflow/map_dim_shuffle.py, tests/transformations/map_dim_shuffle_test.py
The reordering of the dimension was quite strange, it is now much more cleaner. Furthermore, the `tile_sizes` parameter of the map range was ignored, i.e. not changed. Furthermore, the parameters are now correclty copied. Before it was just assigned, thus if later the parameter list of the map was again changed this effect would propagate to _all_ maps that where treated.
=> Updated and fixed the MapDimShuffle tranformation.

dace/builtin_hooks.py, dace/frontend/operations.py
There is currently a bug in the profiler, that the first run recorded includes the runtime of all the warmup runs, making one ugly outlier. This is because `times[0]` is set before the warmups and is never properly reset.
This fixes that and makes the surrounding code a bit cleaner (e.g. using `np.diff` instead of list comprehension).
I also added some options that make the profiler more usable when it's called inside of other `tqdm` progress bars (allows setting `tqdm`'s `leave=False` and stop it from printing results).
List of changes:
- Fix: timing error
- Add: `tqdm_leave` parameter
- Add: `print_results` parameter
- Cleanup: Only print `Profiling...` if `tqdm` is not used
- Cleanup: use `warnings.warn()` instead of `print("WARNING: ...")`
- Cleanup: remove unused variable for return …
=> Fix Profiler + Minor improvements

dace/sdfg/state.py
It is now possible to add conditions and assignments directly to them. Furthermore they also support now `is_start_block` flag.
=> Updated the `add_state_{after, before}()` function.

dace/config_schema.yml
For the 0.16 release, we want to introduce the change to the default of `serialize_all_fields` to `False`.
This reverts PR "Changed default of serialize_all_fields to True #1470".
This reverts commit bfe4163f1297e049921c40e2a1bcb208fccc076b.
=> Changed default of serialize_all_fields to False

dace/frontend/python/newast.py
The refactoring of Views in PR #1504 led to the creation of the ArrayView type. This PR addresses an issue in the Python ProgramVisitor, where ArrayViews are not recognized properly as Views (of Arrays), leading to a NotImplementedError. The fix is simple: when checking if a container is an Array or a View (of an Array), instead of making a direct equality comparison to Array or View, a subclass comparison against Array is performed. The latter returns true if the container is an Array or any Array subclass, including ArrayViews.
=> Adds support for ArrayView to the Python Frontend

dace/cli/sdfv.py, dace/sdfg/sdfg.py
Beside making it possible to suppress the output of `sdfv.view`, this commit also changed the default behaviour of `SDFG.view()` by no longer outputting in which file it was saved.
=> It is now possible to suppress output in `view()`

dace/sdfg/sdfg.py
This PR corrects the `SDFG.__init__` docstring to refer to the correct parameter `constants` (compile-time constants) instead of `symbols` (scalars that are immutable in the SDFG scope). See also #1563
=> Correction in the docstring of the SDFG class's init method

dace/frontend/python/preprocessing.py, tests/python_frontend/unroll_test.py
Looking at: https://github.com/spcl/dace/issues/1568
The code was blindly calling down to a `_visit_potential_constant` which is written for single element rather collection of them. Unroll the list, like the `dict` is done in the `if` above.
=> Fix Subscript literal evaluation for List

.github/workflows/pyFV3-ci.yml
Fixes various smaller issues of the Pace CI:
- Removed installation command for non-existent `gcc-13` package
- Adds Pace CI to merge queue (see: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
- Adds `apt-get update` before `apt-get install`
- Adds `-y` flag to `apt-get install`
=> Removed GCC 13 from Pace CI

dace/sdfg/sdfg.py
I noticed that it would be cool if I could write `sdfg.save("~/tmp/faulty.sdfg")` and it would save it into my home directory, instead in a directory `./~` in some random directory.
=> `SDFG.save()` now performs tilde expansion.

dace/config_schema.yml
Our documentation already states that DaCe requires a C++14 capable compiler: https://spcldace.readthedocs.io/en/latest/setup/installation.html#dependencies
Additionally, Xilinx Vitis HLS does support C++14. It just wasn't enabled (instead, C++11 support was enabled).
=> Changed Xilinx C++11 flag to C++14

dace/sdfg/analysis/cfg.py, dace/transformation/passes/constant_propagation.py, dace/transformation/passes/prune_symbols.py, tests/passes/constant_propagation_test.py
Constant propagation fails for certain graph structures due to an issue with `dace.sdfg.graph.Graph.topological_sort`. This is related to #1560.
=> Fix constant propagation failing due to invalid topological sort

dace/config.py, tests/config_test.py
The context manager uses `NamedTemporaryFile` to store the current configuration, to later restore them. Instead of passing the file object directly to the save function, it just passes the file name, i.e. the save (and the load function) will open the file again, which is in itself not a problem. However, on the Github Windows image this leads to a permission error (using the created file object is fine).
This commit solves this by adding the `file` argument to `Config.save()` that allows to pass a file object directly to the function. The same change is applied to the load function of the config object.
=> Use file object directly in `temporary_config()`

dace/codegen/targets/cuda.py, dace/codegen/targets/fpga.py, dace/codegen/targets/framecode.py, dace/sdfg/graph.py, dace/sdfg/state.py
This is currently work in progress to see how we can best fix this misleading naming.
Fixes https://github.com/spcl/dace/issues/1560
Since https://github.com/spcl/dace/issues/1560 is still in flux, we have to make sure the PR stays in sync with what we are discussing in https://github.com/spcl/dace/issues/1560.
Additionally, at the call-sites of the _previous topological_sort_ (before renaming), there are various comments to use a topoligical sort. After the renaming, they become misleading, so we should probably fix/improve those comments.
=> Rename misleading topological_sort to bfs_nodes

dace/codegen/compiled_sdfg.py, dace/sdfg/validation.py, tests/sdfg/scalar_return.py
Due to how the code generator works a scalar return value is not possible and it does not generate an error.
Returning a scalar is a desired feature as there is code in `CompiledSDFG` for that, but it does not work.
The frontend works around this by simply promoting everything to an one dimensional array.
This commit introduces:
- A change to validate to reject such SDFGs.
- A test that can test the feature, but is disabled, since it does not work.
- A test for the new restriction.
=> Scalar return values are now invalid

dace/transformation/passes/transient_reuse.py
Added a flag to the `TransientReuse` transformation that prevents the transformation from unconditional printing of memory savings.
This commit changes the default behaviour, because now the report is not printed, but must be explicitly activated.
=> Made `TransientReuse` Less Verbose

dace/codegen/targets/cpu.py, dace/codegen/targets/fpga.py, dace/sdfg/nodes.py
Before it was only possible to specify if a Map should be unrolled or not, i.e. if `#pragma unroll` should be added or not.
However. the pragma accepts an argument, the most interesting use case for this is to _prevent_ unrolling, i.e. adding `#pragma unroll 1`.
I solved this by adding a new property `unroll_factor` to the map that takes an integer, i.e. the argument.
I am open for other suggestions to solve this problem.
As a wrote the most interesting use case (and in fact our motivation for this fix) is the ability to prevent unrolling explicitly.
=> Improving the Usage of `#pragma unroll`

dace/transformation/__init__.py
It was very inconvenient, as `PatternTransformation` can be imported from `dace.transformation` but the node has to be imported from `dace.transformation.transformation`.
=> Added `PatternNode` to `dace.transformation` imports.

dace/codegen/targets/framecode.py
Updated for v0.16: The (renamed) `BasicCFBlock` class still requires 4 arguments in a different order and with none being optional. The new `__init__` method as provided by `@dataclass` looks like this:
```python
def __init__(self,
dispatch_state: Callable[[SDFGState], str],  # from ControlFlow
parent: Optional['ControlFlow'],  # from ControlFlow
last_block: bool,  # from ControlFlow
state: SDFGState,
)
```
The current code still supplies 3 arguments and in a wrong order. This PR fixes that.
Original PR description (when I was still running on DaCe v0.15.1) follows.
---
With `optimizer.detect_control_flow == False`, this part of code causes an error later on:
```text
File "/home/ibug/examples/dace/dace/codegen/control_flow.py", line 221, in as_cpp
expr += elem.as_cpp(codegen, symbols) …
```
=> framecode: Fix missing BasicCFBlock argument

dace/subsets.py
Before all cover functions ignored the case if the subsets have different lengths. The effect was that the subsets `A = Range.from_string("i, k, 0:N, 1")` and `B = Range.from_string("i, k")` would cover each other. This case was considered undefined behaviour.
This commit changes the behaviour of these function such that for covering it is required that the subsets must have the same dimensions.
=> Specified behaviour of `Subset.covers()` for different dimensionality

dace/transformation/interstate/loop_detection.py, dace/transformation/interstate/loop_peeling.py, dace/transformation/interstate/loop_to_map.py, dace/transformation/interstate/loop_unroll.py, dace/transformation/interstate/move_loop_into_map.py, dace/transformation/interstate/trivial_loop_elimination.py, dace/transformation/transformation.py, tests/transformations/loop_detection_test.py, tests/transformations/loop_to_map_test.py
Generalizes the behavior of loop detection to support rotated loops, single-state loops, and as a result LLVM canonical loops. The PR also refactors the loop analysis methods and generalizes `DetectLoop` transformation subclasses, such as `LoopToMap` and `LoopPeeling`.
=> More robust loop detection

dace/transformation/passes/constant_propagation.py, tests/passes/constant_propagation_test.py
There is a bug related to the missed exploration of interstate edges during constant propagation in case a loop body has a conditional assignment. The reverse DFS yields parent-node pairs and analyzes only the edge connecting the two. The DFS will yield a certain node only once, while the assumption in the code is that the uniqueness is enforced on the parent-node pair. This results in only one outgoing interstate edge per body state being visited, leading to mistakes in the common case of conditional assignments (which result in two outgoing edges performing different assignments). If the visited edge does not perform an assignment or assigns the initialization value, the symbol will be wrongly interpreted as a constant and replaced in downstream states.
A short reproducing example is: …
=> fix missed exploration of edges in constant propagation

dace/transformation/transformation.py, tests/transformations/apply_to_test.py
Before there was only the `apply_to()` function which allowed to perform the transformation. However, sometimes when transformations are composed it is useful to be able to check if a transformation could be applied later. Sometimes this follows directly from the operation that is currently done, but sometimes it is not easy to check it.
=> Added  `can_be_applied_to()` To Transformation Interface

dace/frontend/python/newast.py
Minor QOL feature: print the exception early when failing parsing. When debugging code base that are 8 or 9 level of class/functions deep, it helps with obvious errors.
=> [Minor] Print out exception on parsing fail early

dace/dtypes.py, dace/properties.py, dace/sdfg/nodes.py, dace/sdfg/state.py, dace/serialize.py
Before there were `optional` and `optional_condition` (which had the oposite meaning, i.e. not optional if the callable evaluates to `True`). This was all replaced by the `serialize_if` callable, which if it returns `True` what the default does the property is serialized and if it rerturns `False` the property is not serialized. This commit also introduces the `dtypes.CPU_SCHEDULES` collection.
=> Reworked Optional Serializing

dace/properties.py, dace/sdfg/replace.py
Because of the implementation of the `__set__()` and `__get__()` functions such properties modeled an immutable set, by essentilly copying the value that was assigned to it and returning a copy of the internal set. However, because `__get__()` returned a regiular `set` this object was mutable, but all mutation did not affect the property, which is a rather unintuitive behaviour.
The effect is, that every single `assert` in the code bellow fails.
```
import dace
@dace.properties.make_properties
class Test:
member = dace.properties.SetProperty(element_type=int)
def __init__(self):
self.member = set()
a = Test()
assert a.member is a.member
a.member.add(10)
assert len(a.member) == 1
assert 10 in a.member
```
It is important that even if the first assert is removed the second two asserts will …
=> Modified `SetProperty`

dace/sdfg/state.py, tests/sdfg/state_test.py
Before if the user wanted to supply in and output nodes he had to present a `dict` that maps the data name to the access node. However, because of the rules of a valid SDFG the key of that `dict` was always the same as the data the access node this information is redundant. Thus this commit allows to only pass the access nodes.
=> Made the `SDFGState.add_mapped_tasklet()` more convenient

dace/transformation/dataflow/stream_transient.py, dace/transformation/passes/constant_propagation.py, dace/transformation/transformation.py, tests/passes/constant_propagation_test.py
Propagating multiple constants symbolically at the same time is not a good idea if propagated symbol A can change a value that affects propagated symbol B. This PR adds a failing test and hopefully a fix.
@luigifusco @phschaad
=> Bug in constant propagation with multiple constants

dace/frontend/common/einsum.py, dace/libraries/blas/nodes/gemm.py, tests/numpy/einsum_test.py
Follow up to #1620.
Replaced more `==` with `equal_valued`, since SymPy 1.13 changed the semantics of `==` for their symbolic expressions.
=> Changed more `==` to `equal_valued`

dace/data.py, dace/frontend/common/distr.py, dace/frontend/python/newast.py, dace/sdfg/nodes.py, dace/sdfg/sdfg.py, dace/sdfg/validation.py
This PR adds checks to the SDFG to ensures that names from symbols, data descriptors and so on are unique.
Furthermore, it also ensures that the NestedSDFG validates correctly and ensures that no symbols can be written.
=> Better Name Validation

dace/codegen/dispatcher.py, dace/transformation/passes/constant_propagation.py, dace/transformation/passes/reference_reduction.py, tests/passes/constant_propagation_test.py, tests/sdfg/reference_test.py
* Fixes a case where constant propagation would cause an inter-state edge assignment race condition
* Fixes reference-to-view disconnecting a state graph and causing a race condition
* More informative error message in code generation for copy dispatching
=> Fix race conditions in Constant Propagation and Reference-To-View

dace/frontend/fortran/fortran_parser.py, dace/frontend/python/replacements.py, dace/memlet.py, dace/transformation/dataflow/bank_split.py, tests/codegen/dependency_edge_test.py, tests/fpga/multibank_copy_fpga_test.py, tests/inlining_test.py, tests/passes/access_ranges_test.py, tests/sdfg/reference_test.py, tests/transformations/prune_connectors_test.py
Follow up on the discussion in #1678.
Supports `src[expr] -> dst[expr]`, `src[expr] -> [expr]`, and `[expr] -> dst[expr]` initializations for memlets. Also improves memlet label printouts.
@philip-paul-mueller @phschaad the expression mentioned in the other PR will now be printed as `[0, 0] -> B[0]` for clarity and can be reparsed.
=> Improve memlet label and string initialization

dace/sdfg/sdfg.py
1. Do not throw error if `clear_instrumentation_reports()` does not have anything to clear. (The function is useful to avoid accumulating many, many obsolete profile data files over time)
2. Put some more information in a warning message.
=> Some very minor improvement in one error handling and one warning message.

dace/transformation/dataflow/trivial_tasklet_elimination.py, tests/transformations/trivial_tasklet_elimination_test.py
Extend the transformation `TrivialTaskletElimination` for the case where the input or output of the copy-tasklet is a map node.
The following SDFG:
is transformed to this SDFG:
=> Extend TrivialTaskletElimination for map scope

dace/sdfg/state.py, tests/sdfg/state_test.py, tests/transformations/move_loop_into_map_test.py, tests/transformations/prune_connectors_test.py, tests/transformations/refine_nested_access_test.py
During my work on the [new map fusion](https://github.com/spcl/dace/issues/1643) I discovered a bug in `SDFGState._read_and_write_set()`.
Originally I solved it there, but it was decided to move it into its own PR.
Lets look at the first, super silly example, that is not useful on its own.
The main point here, is that the `data` attribute of the Memlet does not refer to the source of the connection but of the destination.
BTW: The Webviewer outputs something like `B[0] -> [0, 0]` however, the parser of the Memlet constructor does not understand this, it must be written as `B[0] -> 0, 0`, i.e. the second set of brackets must be omitted, this should be changed!
From the above we would expect the following sets:
- Reads:
- `A`: `[Range (0, 0)]`
- `B`: Should not be listed in this set, …
=> Fix to Read and Write Sets

dace/codegen/prettycode.py
The diff should be self-explanatory
=> fix(codegen/prettycode): Use base_indentation as intended

dace/sdfg/state.py, tests/codegen/argumet_signature_test.py
This PR fixes the way how arguments are detected in scopes.
Technically this only affects GPU code generation, but it is a side effect of how the code is generated.
In GPU mode a `Map` is translated into one kernel, for this reason a signature must be computed (this is the reason why CPU code generation is not affected, no function call is produced).
To compute this signature the `unsorted_arglist()` function scans what is needed.
However, this was implemented not correctly.
Assume that AccessNode for array `A` is outside the map and inside the map a temporary scalar, `tmp_in` is defined and initialized to `tmp_in = A[__i0, __i1]`, see also this image:
If the `data` property of the Memlet that connects the MapEntry with the AccessNode for `tmp_in` is referencing `A` then the (old) …
=> Modified `SDFGState.unordered_arglist()`

dace/config_schema.yml, dace/sdfg/validation.py, tests/sdfg/warn_on_potential_data_race_test.py
Re-implement changes made by @luca-patrignani in #1541, see that PR for more information.
Author: @luca-patrignani
=> Warn on potential data races

dace/codegen/targets/cuda.py, dace/codegen/tools/type_inference.py, dace/dtypes.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/sdfg/infer_types.py, dace/sdfg/sdfg.py, dace/sdfg/validation.py, dace/transformation/dataflow/warp_tiling.py, dace/transformation/helpers.py, tests/dynamic_tb_map_cudatest.py, tests/numpy/array_creation_test.py, tests/numpy/map_syntax_test.py, tests/python_frontend/device_annotations_test.py, tests/python_frontend/type_statement_test.py, tests/sdfg/cycles_test.py
The PR adds a new syntax to support inline storage specification with the `@` operator, supporting the following statements: `a = np.ones(M) @ dace.StorageType.CPU_ThreadLocal`.
This PR also fixes multiple minor issues in the Python frontend:
=> Python frontend stability and inline storage specification

.github/workflows/fpga-ci.yml, .github/workflows/general-ci.yml, .github/workflows/gpu-ci.yml, .github/workflows/hardware_test.yml, .github/workflows/heterogeneous-ci.yml, .github/workflows/pyFV3-ci.yml, .github/workflows/verilator_compatibility.yml
GitHub Actions workflows use outdated versions of
- actions/checkout
- actions/setup-python
These actions are built for specific node versions, which are now end of life. While the workflows continue to run, GitHub issues a warning (visible in the online interface) and runs them with newer versions of node.
Since both, checkout and setup-python, are basic actions, none of the features that DaCe workflows are using changed. We might see slight speedup from out of the box caching added to setup-python in recent versions.
Parent issue: https://github.com/GEOS-ESM/SMT-Nebulae/issues/89
=> CI: Update checkout and setup-python actions

dace/codegen/compiler.py, dace/config_schema.yml
Add back clang-format.
I generated with a style file, without a style file, and without clang format (uninstalled clang-format for this). SDFGs generate. I can add tests.
=> Add back clang-format support

dace/codegen/targets/cpp.py, dace/sdfg/validation.py
Small quality of live PR that improves two error messages. Especially if the state was called `state` (as per default), it was hard to parse at first sight
For some reason, `yapf` was also changing the formatting of other code parts. I thus made two commits
1. Format the two files that I was about to edit.
2. Improve the error messages in the freshly formatted files.
This allows to separate real changes from purely stylistic ones.
Would it be an idea to enforce linting with a GitHub Actions workflow? I'm happy to write an issue about this (and contribute early next year).
=> Quality of live: Improved error messages

dace/frontend/fortran/ast_components.py, dace/frontend/fortran/ast_utils.py, tests/fortran/ast_utils_test.py, tests/fortran/fortran_language_test.py
Replace some of the invalid fortran test programs with valid ones (that passes under `gfortran -Wall`). This breaks some of the tests, so add fix for them too. `test_fortran_frontend_loop1()` still has an invalid test program, but the nearest valid one breaks for a different reason, and will be fixed later.
=> Used valid FORTRAN test program for a couple frontend tests + Made `floatlit2string()` convert the FORTRAN real literal strings into python floats.

.github/workflows/pyFV3-ci.yml
According to @phschaad, the pyFV3 workflow occasionally fails with connection refused errors when attempting to download the test data set for regression testing. This PR configures `wget` to retry even in case of fatal connection errors (like 404 (not found) or 503 (connection refused)).
Let's see if this helps in the short term. In the long run, we should think about leveraging caches for that data because it rarely changes and it's kind of a wast to download it every time from scratch.
Follow-up PR from https://github.com/spcl/dace/pull/1731#issuecomment-2458989370.
/cc @FlorianDeconinck FYI
=> CI[pyFV3]: retry even when connection is refused

dace/cli/sdfg_diff.py
Addresses this problem: https://stackoverflow.com/a/67193166
This would be useful if we want to use this library to compare graphs in the unit tests.
=> Make the import of `typing.Literal` portable between python versions 3.7 and 3.12

dace/codegen/targets/cpu.py, tests/codegen/allocation_lifetime_test.py
=> Fix OpenMP dynamic loop bounds that use persistent memory

dace/frontend/fortran/ast_utils.py, tests/fortran/recursive_ast_improver_test.py
Currently it does not work without explicitly adding everything to be used on an `only`-list.
=> [Multi SDFG branch, Fortran frontend] Make `eliminate_dependencies()` support `use lib` without `only`.

dace/frontend/fortran/ast_utils.py, tests/fortran/prune_unused_children.py, tests/fortran/recursive_ast_improver_test.py
`list_of_module_vars` is not actually a string list of the variables, but a structure that needs to be unfolded to get the list.
Also, added additional tests that trigger this case.
=> `list_of_module_vars` is not actually a string list of the variables, but a structure that needs to be unfolded to get the list.

dace/symbolic.py, tests/passes/dead_code_elimination_test.py
Strings like `not ((N > 20) != 0)` (== `Not(Ne(Gt(N, 20), 0))`) were incorrectly interpreted by `sympy.sympify` as constant "False". This is a limitation by sympy, which does not assume integer 0 to be a Falsy, and enforces exact equivalence (or difference) checks with `Ne`. To get around this limitation, the DaCe internal AST preprocessor now replaces constants with boolean values if they are arguments to Comparison operations, where the other operand is also a comparison operation, thus returning a boolean.
This fixes an issue with `DeadStateElimination`, closing issue #1129.
=> Fix `pystr_to_symbolic` not correctly interpreting constants as boolean values in boolean comparisons

dace/runtime/include/dace/math.h, dace/runtime/include/dace/nan.h, dace/runtime/include/dace/pi.h, dace/runtime/include/dace/types.h, tests/numpy/constants_test.py
Both $\pi$ and `NaN` are implemented as classes in DaCe.
However, these classes where not marked as device, thus they are only available on the host.
This PR:
- Fixes this for `NaN` and $\pi$.
- Extend the implementation.
- Adds tests for them.
=> Fixed `dace::math::pi` and `dace::math::nan` on GPU

dace/sdfg/analysis/schedule_tree/treenodes.py, dace/transformation/passes/scalar_to_symbol.py, tests/passes/scalar_to_symbol_test.py
=> Make scalar to symbol promotion robust to node order in state

dace/frontend/fortran/fortran_parser.py, tests/fortran/multisdfg_construction_test.py
- Much of the code in the new function is taken from `create_sdfg_from_string()`. However, there are some small changes, so it is written as a new function without modifying `create_sdfg_from_string()`, to minimize the changes needed across the tests. We can update the tests incrementally.
- Some changes were necessary in the ASTTranslation part. Does not break any tests, as far as I can tell.
=> [Multi SDFG, Fortran] Extract the "internal AST construction -> SDFG construction" into a separate function, that also supports multiple entry points.

dace/frontend/fortran/ast_components.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/create_internal_ast_test.py, tests/fortran/fotran_test_helper.py, tests/fortran/multisdfg_construction_test.py, tests/fortran/prune_unused_children_test.py
Testing the internal SDFG construction will allow us to verify if the transforms that follow at least start from a valid input state. One of the added tests (`test_subroutine_contains_function()`) already demonstrates that the construction is not always correct.
=> [Multi SDFG, Fortran, After PR#1774] New tests. In particular, now we can start testing the construction of internal SDFG.

dace/frontend/fortran/ast_utils.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/deconstruct_procedure_calls_test.py, tests/fortran/prune_unused_children_test.py, tests/fortran/recursive_ast_improver_test.py
This involves:
1. Find the bound subprogram for that procedure.
2. Replace the calls to the procedure with that subprogram (with the object as an extra argument).
3. Adding `use` statements as necessary.
This has many, many corner cases not addressed. Will be adding more tests as we refine it.
=> [Multi SDFG, Fortran] Deconstruct all the class procedures of a Fortran program, right after parsing it in.

dace/transformation/interstate/gpu_transform_sdfg.py, tests/transformations/gpu_transform_test.py
Fix GPU transform mapping free access nodes always to GPU storage 
This results with tasklets running on host, that want to write to or read from data marked as GPU storage.
=> Fix GPU transform mapping free access nodes always to GPU storage 

dace/frontend/python/newast.py, dace/frontend/python/parser.py
Found two unused imports and an unused variable. From other code, I inferred that you follow the convention to prefix unused (return) variables with underscores.
I noticed that running `yapf` (as suggested in the contribution guidelines) modified the files in places that I didn't touch. I thus separated the pure formatting changes in the first commit. As argued in PR https://github.com/spcl/dace/pull/1731, I think it would be beneficial (for the project) to enforce formatting as part of the CI. @phschaad not sure if you got to discuss this in the weekly DaCe meeting. I started a discussion page https://github.com/spcl/dace/discussions/1804 and I'm happy to contribute a corresponding workflow early next year (assuming we agree).
=> Cleanup unused imports

dace/frontend/python/newast.py, dace/frontend/python/parser.py
Author: @romanc
@romanc is on leave for the next few days, thus I have replayed the changes made in https://github.com/spcl/dace/pull/1808 here for faster turnaround.
=> Unused imports backport (successor to #1808)

dace/frontend/fortran/intrinsics.py, tests/fortran/fortran_test_helper.py, tests/fortran/intrinsic_blas_test.py
Added two intrinsics needed by ICON: gemm & transpose. Both use DaCe's library node, so they should generate optimal code.
=> Additional intrinsics for Fortran frontend

dace/dtypes.py, dace/sdfg/nodes.py, tests/sdfg/nodes_test.py
For a Map one must always perform two calls (one to `Node.add_in_connector()` and `Node.add_out_connector()`), both calls are different, but highly related. This commit added a new function to the `Map{Entry, Exit}` classes that allows to combine these two calls into one.
=> Added a function `add_scope_connectors()` to the `Map{Entry, Exit}`

dace/sdfg/utils.py, dace/transformation/passes/array_elimination.py, dace/transformation/passes/lift_struct_views.py
`LiftStructViews` is a necessary pass for ensuring structure member accesses and container array accesses work correctly, by lifting accesses to them into a 'tower of views' that correctly traces their accesses to the root data container. However, this previously did not consider interstate edges. This PR fixes this by making two changes:
- Allow `LiftStructViews` to lift struct accesses on interstate edges to the correct tower of views, by inserting a lifting state right before the interstate edge, where views are constructed. The interstate edge is then re-written to access the correct view instead.
- Fix `ArrayElimination` to correctly handle these views, which are not directly connected to other nodes, by preventing it from incorrectly merging or removing them. This is done by …
=> Let LiftStructViews lift interstate edge struct accesses to views

dace/codegen/targets/cpu.py, dace/codegen/targets/framecode.py, dace/sdfg/validation.py, tests/interstate_assignment_test.py
If a symbol is passed as an argument to the SDFG and assigned on an interstate edge, the framecode declares the scalar symbol again. This PR fixes that issue.
The case: If there is an interstate assignment on a variable, `N=5`, but if 'N` is also an input argument to the SDFG, then the generated code does not compile because `N` is redeclared.
=> Symbol redeclaration fix

dace/transformation/dataflow/map_expansion.py, tests/transformations/map_expansion_test.py
The transformation did not consider maps that are connected with dependency edges.
Now, the transformation skips dependency edges if non-dependency edges exist.
Otherwise, it connects the inner and outer maps with a single dependency edge to maintain connectivity.
=> Fixed MapExpansion Transformation

dace/frontend/python/parser.py, dace/frontend/python/preprocessing.py, tests/python_frontend/callee_autodetect_test.py
Fixes cases in which the user has no control over undecorated nested function calls, which previously led to unclear and unrelated `pyobject` type errors.
=> Ignore type hints in undecorated parsed function calls

dace/codegen/compiled_sdfg.py, dace/frontend/python/newast.py, tests/codegen/external_memory_test.py, tests/python_frontend/argument_test.py, tests/python_frontend/return_value_test.py
* Properly parse `return` statements without a return value
* Fix missing argument detection when no arguments are given
=> Python frontend fixes for return values and arguments

dace/sdfg/validation.py, tests/python_frontend/return_value_test.py
The check disallowed valid cases where return values that are not returned to the Python frontend were disallowed. Scalar return values in nested functions take the form of a reference, which is not supported with our current Python bindings.
=> Refine condition for prohibiting scalar return values

dace/frontend/python/newast.py, dace/frontend/python/parser.py, dace/frontend/python/replacements.py, tests/numpy/reductions_test.py, tests/python_frontend/callback_autodetect_test.py
* Implement `numpy.any` and `numpy.all`
* More descriptive errors when slicing and using non-annotated callbacks
* Remove `dace.compiletime` arguments from symbolic analysis
=> Implement numpy.any/all, more descriptive Python frontend errors

dace/frontend/python/memlet_parser.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/runtime/include/dace/math.h, dace/runtime/include/dace/types.h, tests/inlining_test.py, tests/numpy/advanced_indexing_test.py, tests/numpy/ndarray_attributes_methods_test.py, tests/passes/writeset_underapproximation_test.py
=> Python: Support complex left-hand side expressions, argmin/max

dace/sdfg/sdfg.py, tests/sdfg/interstate_assignment_test.py
If the internal method `SDFG._replace_dict_keys` is called with the same `old` and `new` keys, then the method erroneously removes the entry for the specific key completely. Such a case occurs when calling `SDFG.replace_dict` with a dictionary that contains identity replacement matches.
This PR addresses the issue by:
=> Fixes replacement of dict keys

dace/frontend/fortran/ast_desugaring.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/ast_desugaring_test.py
Turns out this is enough to remove all `allocated()` calls that remains after pruning.
=> [Multi SDFG, Fortran] Track down `allocated()` calls on Fparser and resolve them to constants with config injection if possible.

dace/cli/sdfv.py, dace/codegen/targets/framecode.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/libraries/standard/nodes/reduce.py, dace/sdfg/sdfg.py, dace/transformation/passes/fusion_inline.py
- Allow the use of compression when using `SDFG.view`, allowing large SDFGs to be viewed
- Fix codegen issues related to out-of-date CFG lists
- Allow pass options to be passed to `SDFG.simplify`, passing them along to passes
- Implement the pass options API for `InlineSDFGs`
- Fix serialization issues for reduction library nodes where the identity function is `np.inf` or similar non-numeric numbers, which cause issues with other JSON deserializers that do not treat 'Infinity' (or similar) as a number.
- Fix missing symbol arguments when parsing a nested SDFG which takes a structure argument where a member's size is defined by a symbol not explicitly passed to the NSDFG, using symbol mappings
- Fix an error where the frontend reports missing symbols when a scalar struct member is being …
=> Various Fixes and QOL improvements

.github/workflows/general-ci.yml, dace/frontend/python/replacements.py, doc/setup/installation.rst, setup.py, tests/python_frontend/method_test.py
With this we adopt the currently officially supported versions of Python: https://devguide.python.org/versions/
=> Change supported python versions to 3.9-3.13

dace/frontend/python/memlet_parser.py, dace/frontend/python/newast.py, dace/frontend/python/replacements.py, dace/sdfg/sdfg.py, dace/sdfg/utils.py, dace/sdfg/validation.py, dace/transformation/passes/scalar_to_symbol.py, dace/transformation/passes/simplification/prune_empty_conditional_branches.py, tests/numpy/advanced_indexing_test.py, tests/numpy/split_test.py, tests/python_frontend/callee_autodetect_test.py
* Adds support for multi-dimensional integer arrays as indices
* Adds support for mixing advanced and basic indexing (see https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing)
* Adds support for `newaxis` in conjunction with advanced indexing
* Fixes array indirection promotion for multidimensional slices with offset dimensions
=> Fully implement NumPy advanced indexing for reads

dace/transformation/passes/scalar_to_symbol.py, tests/passes/scalar_to_symbol_test.py
Fixes a reported failure mode of scalar to symbol promotion.
=> scal2sym: Fix incorrect dimensionality in indirection removal

dace/frontend/fortran/ast_internal_classes.py, dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/noncontig-pardecls.py
This PR adds support for non-contiguous array slicing in Fortran:
```
cols = (1, 3, 7)
func( arr(1, cols) )
```
It works on 1D and 2D arrays. Pending work: ECRAD issues.
=> Support non-contiguous arrays in Fortran

dace/sdfg/sdfg.py
The logical mistake has been fixed there a long time ago.
=> [f2dace/dev, Fortran] Copy `_replace_dict_keys()` implementation from `main` branch.

dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/elemental_test.py
We replace prior and problematic existing elemental expander with a new one, that uses a single loop expansion base for array2loop, elemental intrinsics, and now elementals + couple bugfixes.
Works on isolated ECRAD samples. This one is not fully verified yet because we fail earlier at SDFG generation due to missing symbols.
=> Replace buggy elemental handling with new approach

dace/sdfg/sdfg.py
I think this change would be convenient, allows us to skip some passes even if we call sdfg.simplify()
=> Add skip to sdfg dot simplify

dace/dtypes.py, dace/frontend/fortran/ast_components.py, dace/frontend/fortran/ast_internal_classes.py, dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/fortran_language_test.py, tests/fortran/missing_func_test.py
1) During call translation, look harder for the subprogram defs (i.e.,  look into the whole AST, including internal subprograms if any).
2) Simplify that path of `call2sdfg()`.
3) Add `internal_subprogram_part` to the subprogram nodes consistently.
4) Make sure that other transforms don't accidentally drop the internal subprograms.
=> [f2dace-dev, fortran] 1) Simplify and improve `call2sdfg()` 2) Do not drop internal subprograms in internal AST transforms.

dace/frontend/fortran/ast_components.py, dace/frontend/fortran/ast_desugaring.py, dace/frontend/fortran/ast_internal_classes.py, dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/ast_utils.py, dace/frontend/fortran/fortran_parser.py, tests/fortran/advanced_optional_args_test.py, tests/fortran/allocate_test.py, tests/fortran/empty_test.py, tests/fortran/intrinsic_basic_test.py
- Allows enabling `empty_test`: fixes writing "true" or "false" into SDFG branches.
- Fixes a bug in the fparser processing, where an optional argument might have been fixed to one value, even if it would not be present some of the times.
- Fixes mishandling of internal subprograms by the optional argument transform.
=> [f2dace/dev, fortran] Write "1" or "0" instead of "True" or "False" as preferred by dace semantics.

dace/transformation/passes/analysis/analysis.py, tests/passes/find_exclusive_data_test.py, tests/passes/find_single_use_data_test.py
Added `FindSingleUseData` analysis pass
This new pass scans the SDFG and computes the data that is only used in one single place.
Essentially, this boils down to the check how often a data descriptor is accessed
A data descriptor is classified if the following statements are true:
- There is exactly one AccessNode referring to the data descriptor.
- The data descriptor is not referred to on an interstate edge, nor in the condition parts of `ConditionBlock`s or `LoopRegion`s.
This pass will be needed to speed up fusion passes.
=> Added `FindSingleUseData` Pass

dace/sdfg/sdfg.py, tests/transformations/prune_connectors_test.py
The `PruneConnectors` transformation relies on `read_and_write_sets()` to identify connectors on a nested SDFG that refer to unused data containers. With the introduction of `ControlFlowRegion` nodes, the data containers can now be accessed by symbolic expressions used as conditions in such nodes. This case was not considered in baseline.
=> Fix read_and_write_sets() for ControlFlowRegion

dace/transformation/passes/dead_state_elimination.py, tests/fpga/vec_sum_test.py, tests/passes/dead_code_elimination_test.py
This PR addresses #1928 by fixing some code in `DeadStateElimination` (DSE) pass. This code was supposed to handle exactly the case reported in the issue, but the check for single branch with unconditional execution was not entirely correct. Test case added.
Includes a change in fpga tests to address a CI error not related to this change:
https://github.com/spcl/dace/actions/runs/13242670532/job/36961472662?pr=1930
=> Fix DSE pass for conditional block with single branch and unconditional execution

dace/frontend/fortran/fortran_parser.py, dace/frontend/fortran/gen_serde.py, tests/fortran/serde_test.py
Now the F90 instrumentation is:
- As before, generate `serde.F90` and put it in ECRAD codebase.
- Add a `use serde` statement inside the `radiation` subroutine from `radiation_interface` module. This will import the following functions/subroutines: `tic()`, `at()`, `serialize()`.
- Add a `call tic()` at the beginning of the execution of `radiation`. This will increase the internal version counter.
- Add `call serialize(at("some/absolute/or/relative/pathprefix"), my_obj)` whenever we need to serialize `my_obj` into a file `some/absolute/or/relative/pathprefix.{VERSION}.data`.  The `at()` function will automatically open a versioned file and return the handler, leaving it open. Then `serialize()` subroutine will write into it, then close it before returning.
- NOTE: serializing arrays …
=> [f2dace/dev, fortran] Avoid writing into (constantly reallocated) strings before writing into file. Also, improve the interface.

dace/frontend/fortran/ast_components.py, dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/icon_config_propagation.py, dace/frontend/fortran/intrinsics.py
It fixes the well-known issue of determining the size of a complex expression involving transposition. Required multiple changes across AST transformations.
No new tests broken, and `get_albedos` compiles.
=> Rewrite type inference to reapply after expression size changes

dace/__init__.py, dace/sdfg/__init__.py, setup.py, tests/tutorials/tutorials.py, tests/tutorials/tutorials_test.py, tutorials/getting_started.ipynb
The tutorial `codegen.ipynb` has a small bug, namely the  `ControlFlowRegion`  is not in the correct namespace (as used in the tutorial).
This PR fixes the issue by importing `ControlFlowRegion` in the `dace` namespace.
Additionally I  added a test for the notebook tutorials to make sure they are not broken.
At the moment I added only the "getting started" and "codegen" notebooks.
These tests require new dependencies `ipykernel` and `nbconvert`.
The above may or may not be the preferred solutions!
=> Fix tutorial codegen

dace/transformation/passes/dead_dataflow_elimination.py, tests/passes/dead_code_elimination_test.py
For this bug to show, we need two separate states with a transient produced in one and subsequently read and written (but not read again). It is important that `StateFusion` isn't able to merge these two state. I've put a dummy if/else in the middle. Before DDE this might look like
where `tmp_computed` is transient and `tmp` is a given variable. DDE will now go and see that `tmp_computed` can be removed as an output of the `read_write` tasklet. The currently faulty update of `access_set` will remove `tmp_computed` from the list of reads in `block` state. This will then propagate (badly) up to the `start` state where `tmp_computed` is marked as never read again, removing the whole tasklet, leaving the `block` state to read an uninitialized `tmp_computed` (if we were to codegen).
```python …
```
=> Fix: DDE removing read from access_set in read/write nodes

dace/transformation/interstate/state_fusion.py, tests/transformations/state_fusion_test.py
Check for all potential match in `_check_paths` to not miss potential `memlets_intersect` failure.
Unit tests for checks the internal `_check_paths` function since it triggers on a non deterministic networkx search.
:warning:  This code exists as-is in `main` as of Feb 26 and showcase the same issue, cherry-picking fix will have to happen :warning:
=> `StateFusion` misses read-write conflict due to early return

.github/workflows/linting.yml, .github/workflows/scripts/show-git-diff.sh, .pre-commit-config.yaml, CONTRIBUTING.md, setup.py, tests/transformations/state_fusion_test.py
As discussed in the weekly DaCe meeting today, we'd like to go ahead with enforcing consistent formatting as part of CI. As a reminder, this started with a discussion[^1] in December and there was no pushback on the discussion page and also not in the meeting today.
We decided to proceed in the following way.
1. @tbennun will run `pre-commit` / `yapf`  locally on the codebase and push that, see https://github.com/spcl/dace/pull/1966
2. This PR wil then be merged afterwards and just contain the changes needed to add the new CI job.
[^1]: https://github.com/spcl/dace/discussions/1804
=> Enforce consistent formatting on CI

dace/codegen/targets/cpu.py, dace/frontend/fortran/ast_transforms.py, dace/frontend/fortran/ast_utils.py, dace/frontend/fortran/intrinsics.py, tests/fortran/intrinsic_merge_test.py
This PR allows fortran's `MERGE` to accept struct references as argument
Beware: the test does not work currently; it segfaults due to incorrect allocation of nested structures by dace.
```cpp
struct test_type {
double* input_data = {};
double* input_data_second = {};
};
struct test_type2 {
test_type* var = {};
};
struct merge_test_state_t {
};
void __program_merge_test_internal(merge_test_state_t*__state, double * __restrict__ input1, double * __restrict__ input2, double * __restrict__ res)
{
test_type2* data_var_0 = new test_type2;
data_var_0->var->input_data = new double DACE_ALIGN(64)[3];
data_var_0->var->input_data_second = new double DACE_ALIGN(64)[3];
```
=> Fix handling of MERGE with data references

dace/transformation/pass_pipeline.py, dace/transformation/passes/fusion_inline.py, dace/transformation/passes/simplify.py
This PR properly implements the `Pass.set_opts()` mechanism.
The format is such that the key must be prefixed with the name of the transformation for which the key should be set.
According to Philipp Schaad this was the intended behaviour, but it was not implemented properly.
Now the function is implemented once in the `Pass` and sub classes does not have to provide their own implementation.
=> Updated/fixed/finalized the `set_opts()` mechanism of the passes.

dace/transformation/interstate/multistate_inline.py
The error was that the state name was only added to the list of known names if it was already known. Assume that the top SDFG had the states with name `name1`, but the nested SDFG had the states `name1` and `name1_0` (the `_0` is the pattern added by the `find_new_name()` function). The error happens if `name1_0` is processed before, because it is not known it was not added to `statements`, then `name1` is processed, because it is known, the parent has a state of the same name, it is passed to `find_name_name()`. That function will then see that `name1_0` is free and use that name. This leads to the error because now two states with the name `name1_0` are present in the SDFG, once the original state (from the nested SDFG) and one the state (from the nested SDFG) that was previously named …
=> Fixed State Renaming in `MultistateInline`

dace/transformation/helpers.py, dace/transformation/interstate/multistate_inline.py, tests/inlining_test.py, tests/transformations/isolate_nested_sdfg_test.py, tests/transformations/mapfusion_test.py, tests/transformations/state_fusion_test.py
This PR addresses [issue#1959](https://github.com/spcl/dace/issues/1959), the issue was about that the inlining transformation destroys the SSA invariant we maintain inside GT4Py.
This invariant states that in every code path there is exactly one AccessNode with that is used to write to a data container.
The PR solves this issue by modifying how the nested SDFG is isolated, before this was done in two steps and is now performed in a single step.
The main idea is that the number of writes is preserved.
=> Updated MultistateInlining

dace/codegen/targets/framecode.py
This code change addresses the following error:
```
callsite_stream.write(
>               '''__state->report.save("{path}/perf", __HASH_{name});'''.format(path=sdfg.build_folder.replace(
'\\', '/'),
name=sdfg.name), sdfg)
E           TypeError: Path.replace() takes 2 positional arguments but 3 were given
```
=> Fix perf path in codegen

dace/sdfg/validation.py
If the validation founds an out of bound access for in the subset of a Memlet that is marked as `dynamic` it will only output a warning. If it however, finds this oob behaviour in `other_subset` it will generate an hard error.
This commit changes this behaviour such that also for `other_subset` only a warning is generated, makes them more uniform.
=> Updated the validation regarding `other_subset`

dace/transformation/dataflow/map_fusion.py, tests/transformations/mapfusion_test.py
This PR adds two new functionalities to `MapFusion`.
Until now it was only possible to fuse two Maps if the intermediate node has a single producer (the top Map).
But this is not strictly required, it can have as multiple producer, the important thing is that the second Map only consumes data that have been written by the first Map.
The second functionality, is actually a fix.
Consider the following situation:
```python
for i in range(10):
tmp[i] = a[i] + 10
for i in range(10):
b[i] = tmp[i] * a[i]
```
Both the first and second Map have an input edge from an AccessNode referring to `a`.
There was a functionality that was supposed to remove the edge going to the second map, i.e. reuse the edge that was going to the first map.
However, this was not properly working and this is fixed.
Note …
=> Updated `MapFusion`

dace/codegen/targets/cuda.py
Memlets that the GPU code generator can not be expressed as a `cudaMemcpy*()` call are turned into Maps.
However, there was an issue because codegen did not make sure that an Memlet it wants to promote is empty.
So it accessed the subsets of an empty Memlets, which are `None` and hits an error.
=> GPU Codegen Expansion of Empty Memlets

dace/sdfg/propagation.py
The function is supposed to return an empty set, but instead returned an empty dict. Now it returns a set as promised. Added a return type such that mypy would complain.
This is a backport of https://github.com/spcl/dace/pull/2007 to `v1/maintenance`.
=> Backport: Memlet propagation: return set - as promised

dace/sdfg/propagation.py
The function is supposed to return an empty set, but instead returned an empty dict. Now it returns a set as promised. Added a return type such that mypy would complain.
=> Memlet propagation: return set - as promised

dace/codegen/targets/cuda.py
While `__dace_init_cuda()` and `__dace_exit_cuda()` where FWD the `__dace_gpu_set_stream()` and `__dace_gpu_set_all_streams()` function where not which prevent their usage in user supplied init and global code fragments.
This PR FWD them at the same location as the init and exit functions.
PS: The names are a bit off, we should either settle on "CUDA" or "GPU" but not on both.
=> GPU Codegen now FWD Stream Functions 

dace/sdfg/utils.py, dace/transformation/interstate/__init__.py, dace/transformation/interstate/condition_fusion.py, tests/transformations/interstate/condition_fusion_test.py
This PR adds the condition fusion transformation which fuses directly consecutive or nested conditional blocks.
=> ConditionFusion Transformation

dace/transformation/dataflow/map_fusion.py, tests/transformations/mapfusion_test.py
In [PR#1993](https://github.com/spcl/dace/pull/1993) the possibility to consolidate or not consolidate edges was added to `MapFusion`.
However, it turned out (at least in GT4Py word) that this was not enough.
Thus, a new mode was added, which allows conditionally consolidation.
Assume, that there are two edges with the subset `[:, 0:10]` and `[:, 1:8]` there is no harm in consolidating the two because one is a superset of the other.
The `consolidate_edges` flag was removed, instead the following flags were added:
- `never_consolidate_edges`: Which blocks all edge consolidation, i.e. all edge will be maintained.
- `consolidate_edges_only_if_not_extending`: Which allows consolidation only if the this does not lead to an increase of the transfered subset.
=> Update Edge Consolidation in `MapFusion`

dace/sdfg/state.py
The issue here is that `find_cycles()` returns a generator, which is truthy even if there are no cycles. The proposed solution is to evaluate the generator. That way, if the generated list is empty, it will be falsy and we won't report cycles if there are none. This allows developers to see the other error message, which is currently unreachable.
=> Only report cycles if we found some

dace/sdfg/utils.py, tests/sdfg/utils_test.py
From what I can tell, `traverse_sdfg_with_defined_symbols()` is supposed to traverse the SDFG, accumulating symbols as it runs down the tree. The current implementation resets the dict of "already known symbols" when recursing down into a state that is the source of an edge. That seems odd. In particular, not even the globally available `sdfg.symbols` are marked as defined anymore with that reset.
The proposed fix passes along already known symbols like in all other cases, ensuring that the dict of known symbols only ever grows.
=> Avoid losing symbols in `traverse_sdfg_with_defined_symbols`

tests/fortran/intrinsic_math_test.py
This small PR removes the duplicate (with same logic) `test_fortran_frontend_log` test from `tests/fortran/intrinsic_math_test.py`.
=> Fix fortran frontend log test

dace/sdfg/propagation.py, dace/transformation/interstate/loop_detection.py, tests/sdfg/work_depth_test.py
Networkx runs into a state space explosion for large loop graphs with many branches when querying simple cycles in the graph. Since state propagation (used by memlet propagation) makes use of that, this causes the operation to not complete in any reasonable time frame. This PR back-ports the improved loop detection from DaCe 2.0 and changes state propagation's loop range annotation to make use of that, instead of relying on Networkx's cycle querying.
=> Fix networkx state space explosion for cycle detection in state propagation

dace/transformation/interstate/__init__.py, dace/transformation/interstate/loop_overwrite_elimination.py, tests/transformations/interstate/loop_overwrite_elimination_test.py
This PR adds a new transformation, which eliminates loops writing to the same memory location in each iteration by replacing them with the last iteration.
Example:
```py
for i in range(10):
A[0] = B[i]
```
is replaced by:
```py
A[0] = B[9]
```
=> Loop overwrite elimination

dace/frontend/python/newast.py, tests/python_frontend/nested_name_accesses_test.py
The issue manifests in methods that mutate the original data container, such as `ndarray.fill`. 
Fixes Issue #2100
=> Properly register input/output data containers for nested programs

dace/frontend/fortran/fortran_parser.py
Turn double-quotes into single-quotes to fix a syntax error.
=> Use single quotes in f-string.

dace/jupyter.py
Fixes a sporadic issue in CI where Jupyter would not connect due to a timeout error, which would be misreported as a test failure.
=> Safer connectivity test for Jupyter

.github/workflows/fpga-ci.yml, .github/workflows/general-ci.yml, .github/workflows/gpu-ci.yml, .github/workflows/heterogeneous-ci.yml, setup.py
Limits each test to 5 minutes. Mitigates hangs in CI and prints potentially-hanging test.
=> CI: Add a timeout for each individual test

dace/transformation/dataflow/map_fusion_vertical.py, dace/transformation/passes/full_map_fusion.py
The transformation already offers the `assume_always_shared` flag, which tells the transformation to assume that the intermediate is shared, which allows to skip the scan of the SDFG.
Intermediate are classified into two categories:
- Shared: Which need to be retained, because they are used somewhere else.
- Exclusive: Only needed to exchange information between the two Maps.
This PR introduces the `require_exclusive_intermediates` flag, which instructs the transformation to only apply if the intermediates are exclusive, i.e. will be removed after the fusion.
It is important that `require_exclusive_intermediates` does not influence the "pure outputs" of the first Map, i.e. the outputs that are not used by the second Map.
To address this the `require_only_intermediates` flag was …
=> Added Fine Grain Control to `MapFusionVertical`.

dace/subsets.py, tests/range_add_test.py
The function was ignoring the `tiling_sizes` property of the `Range` object.
Also added unit tests.
Originally this fix was part of [PR#2096](https://github.com/spcl/dace/pull/2096) but it was wrong, so it was moved to its own PR.
=> Fixed `Range.__add__()`

dace/transformation/dataflow/strip_mining.py, tests/transformations/strip_mining_test.py, tests/transformations/strip_miningy_test.py
**Bug Description:**
To put it simple, the `StripMining` transformation essentially performs tiling- that is, it adds a  **new outer** map which encloses
an existing one, where the new map runs over chunks (=tiles) of the original iteration space, while the inner map handles 
individual elements inside each chunk. The inner map is the original map, where the range just go adapted.
Now, the new (outer) map needs to be connected to the original one, and the dataflow between them must be captured correctly. 
This essentially involves analyzing which parts of a data descriptor should flow for each chunk. For the sake of simplicity, one 
can think of this process as: copying an existing memlet (flowing to and from the original inner map) and update it to create
the correct memlets between the …
=> Fix: Memlets in StripMining transformation

dace/sdfg/utils.py
**Description**
Passing: 
`*list(cfg.all_control_flow_blocks())`
as argument to the function
`cfg.all_edges(..)`
leads to a `KeyError`. The reason is,  that `cfg.all_control_flow_blocks()`  returns `ControlFlowBlock`'s of **nested** `ControlFlowRegion`'s which are not in `cfg._nodes` used by the `all_edges(...)` function.  
If I understand it correctly, the goal of the `_get_assignments(...)` function is to find whether a symbol is written to
via an interstate edge. In this case, using  `cfg.all_interstate_edges()` should fix the issue.
=> Fix _get_assignments()

dace/codegen/targets/cpu.py, tests/codegen/cpp_test.py
When arrays have storage type Register, but are bigger than `max_stack_array_size`, they are moved to the heap. In that situation they are dynamically allocated and need to be deleted again.
In the test, I removed `redundant_array_crashes_codegen_test_original_graph()` which is a setup function of a test that got removed in https://github.com/spcl/dace/pull/2105.
I wasn't sure where to put the test. `codegen/cpp_test.py` seemed logical. The new test is also very close to `tests/vla_test.py` (which tests the same but for variable length arrays). Since that test was explicitly for variable length arrays, I didn't wanna put it there. In any case, I'm happy to move the new test around if you want it somewhere else.
Backport on `v1/maintenace` is in PR https://github.com/spcl/dace/pull/2135.
=> fix: delete big arrays that are moved to heap

dace/sdfg/utils.py, tests/utils/specialize_scalar_test.py
ScalarToSymbol + SDFG.specialize breaks too often, and on f2dace, I wrote this utility function to directly specialize a scalar to a constant.
It does not fail when the scalar is used as a dynamic map connector and used on interstate edges.
(I am not sure if I need to cover the case where the scalar name is the subset of another array name)
(Btw. maybe we should add warnings, if a data descriptor name is subset of another data descriptor because our string replacement functions can create problems there)
=> Specialize scalar utility function

dace/codegen/targets/cuda.py, tests/codegen/gpu_allocation_order.py
**Description**
In `CUDACodeGen`, arrays in a scope should be allocated **after** defining the map variables.
Currently, the allocation happens earlier, which can (and does) lead to code referencing undefined variables.
For example, consider the following part of an SDFG:
Which will generate:
```cpp
B_0 = &gpu_B[((N * (i + 1)) + j)];
```
**before** `j`is defined, resulting in a compiler error.
=> Allocate arrays in scope after map variables are defined

dace/subsets.py
This PR makes the `Indices` class a bit safer to use, a short summary:
- The `{max, min}_elements()` functions were returning a reference to the underlying `self.indices` class, which might lead to an unintended modification of the underlying data. The new solution is that they are shallow copied.
- The constructor was changed, the class can now also be constructed using single pass iterators.
This PR is also a RFC as I found some strange behaviour/cases, I marked them with `Possible Error`.
So could somebody how knows a bit more about the code base take a look at it and check if this behaviour is okay.
=> Updated `Indices`
