spcl/dace

dace/codegen/targets/cpu.py
dace/codegen/targets/xilinx.py

To retain support for math functions (sqrt etc.) inside tasklets

Minor Xilinx code generation fixes

---

dace/sdfg.py
dace/transformation/optimizer.py
dace/transformation/testing.py

New class and unit tests for transformation stability

Automated transformation testing

---

diode/sdfv.html
diode/sdfv.py
diode/templates/sdfv.html
diode/webclient/renderer.js
diode/webclient/renderer_dir/global_vars.js
diode/webclient/renderer_elements.js
diode/webclient/sdfv.css

Various performance and usability improvements for SDFV and the SDFG renderer:
* SDFV now shows node/edge properties (not all of them)
* Hierarchical rendering optimizes large SDFG drawing

Renderer Improvements

---

diode/sdfv.html
diode/templates/sdfv.html
diode/webclient/diode.js
diode/webclient/sdfg_utils.js
diode/webclient/sdfv.js

* More types supported in sidebar
* Refactoring
* Memlet connectors

SDFV renderer improvements v2

---

dace/codegen/targets/framecode.py
dace/frontend/python/newast.py
dace/frontend/tensorflow/winograd.py
dace/sdfg.py
dace/serialize.py
samples/fpga/filter_fpga_vectorized.py
samples/sdfg_api/stencil_boundaries.py
tests/constant_array_test.py

Serialize constant types

---

dace/graph/nodes.py
dace/properties.py
dace/transformation/dataflow/map_fusion.py
diode/webclient/renderer.js
diode/webclient/renderer_dir/global_vars.js
diode/webclient/renderer_elements.js
tests/strict_after_load_test.py

Probably stems from improper saving/loading of the `sdfg_list` property

Fix strict transformations after loading and nice rendering of small graphs

---

dace/codegen/compiler.py

Do not save generated code files unless they changed

---

dace/codegen/cppunparse.py

Fix "_Constant() got an unexpected keyword argument 'infer_type'"

---

diode/webclient/renderer.js
diode/webclient/renderer_dir/dagre.js
diode/webclient/renderer_elements.js

This does not solve all edge drawing issues, but makes the SDFG rendering neater in the average case.

Better drawing of graph edges

---

dace/sdfg.py
dace/subsets.py
dace/transformation/dataflow/map_fission.py
dace/transformation/helpers.py
dace/transformation/interstate/sdfg_nesting.py
tests/mapfission_test.py

Adds tests and fixes various issues in MapFission with multi-state nested SDFGs and complex subgraphs.

Fix various issues in MapFission

---

dace/codegen/compiler.py
dace/frontend/python/newast.py
dace/sdfg.py
tests/numpy/retval_test.py

Return value support for SDFGs

---

dace/codegen/targets/cpp.py
dace/subsets.py
dace/transformation/dataflow/strip_mining.py
tests/transformations/local_storage_test.py

Fix local-storage transformations for uneven partitions

---

dace/runtime/include/dace/math.h
tests/half_cudatest.py

More support half-precision operations in CUDA

---

dace/dtypes.py
dace/libraries/blas/environments/intel_mkl.py
dace/libraries/blas/nodes/__init__.py
dace/libraries/blas/nodes/gemm.py
tests/library/gemm_test.py

Add Gemm Library node and tests

---

dace/transformation/dataflow/stream_transient.py

StreamTransient can now introduce a buffer

---

diode/webclient/renderer.js

Instead of using the middle mouse button to drag elements around, one can now toggle a dedicated object moving mode in which the primary mouse button can be used to move elements. Additionally, the cursor shape more clearly shows the current action.

SDFV: More intuitive dragging controls with seaparate mode

---

dace/properties.py
dace/serialize.py

Pretty SDFG JSON serialization

---

dace/codegen/cppunparse.py
dace/dtypes.py

Use a more intelligent type inference system (would still be better to rely on something external for this?).

Improve type inference

---

dace/codegen/targets/fpga.py
tests/fpga_transpose.py
tests/intel_fpga_test.sh
tests/remove_degenerate_loop.py
tests/remove_single_iteration_loop.py
tests/xilinx_test.sh

Allow assigning FPGA memory banks through the "bank" key in the location dictionary of a data container.

Assign memory banks

---

dace/codegen/targets/fpga.py
tests/fpga_transpose.py
tests/intel_fpga_test.sh
tests/remove_degenerate_loop.py
tests/remove_single_iteration_loop.py
tests/xilinx_test.sh

Remove single iteration loops and replace with simple assignment

---

dace/codegen/targets/cpp.py
dace/codegen/targets/fpga.py
dace/codegen/targets/intel_fpga.py
dace/codegen/targets/xilinx.py
dace/runtime/include/dace/xilinx/access.h
dace/runtime/include/dace/xilinx/stream.h
tests/veclen_copy_conversion.py

Allow copying between container of different memory widths on the FPGA (#228).

Gearboxing memcopies

---

dace/codegen/targets/fpga.py
dace/codegen/targets/intel_fpga.py

Make the check whether a loop is innermost more sophisticated by taking nested SDFGs and unrolled maps into account.
@manuelburger

Innermost loop check

---

dace/codegen/cppunparse.py
dace/codegen/instrumentation/cuda_events.py
dace/codegen/instrumentation/papi.py
dace/codegen/instrumentation/timer.py
dace/codegen/targets/common.py
dace/codegen/targets/cpp.py
dace/codegen/targets/cpu.py
dace/codegen/targets/cuda.py
dace/codegen/targets/fpga.py
dace/codegen/targets/framecode.py
dace/codegen/targets/intel_fpga.py
dace/data.py
dace/dtypes.py
dace/frontend/python/astutils.py
dace/frontend/python/newast.py
dace/frontend/tensorflow/tensorflow.py
dace/frontend/tensorflow/winograd.py
dace/graph/edges.py
dace/graph/nodes.py
dace/properties.py
dace/sdfg.py
dace/transformation/dataflow/map_fission.py
dace/transformation/interstate/gpu_transform_sdfg.py
dace/transformation/interstate/sdfg_nesting.py
samples/fpga/gemm_fpga_stream.py
samples/fpga/jacobi_fpga_stream.py
samples/fpga/jacobi_fpga_systolic.py
samples/fpga/spmv_fpga_stream.py
tests/intel_fpga_test.sh
tests/state_transition_test.py

Property additions/removals

---

dace/codegen/targets/xilinx.py

This was broken for me and the changes fix it, could you have a look @definelicht?

Xilinx Codegen local array definition fix

---

dace/codegen/codegen.py
dace/codegen/codeobject.py
dace/codegen/compiler.py
dace/codegen/prettycode.py
dace/codegen/targets/cpu.py
dace/codegen/targets/cuda.py
dace/codegen/targets/framecode.py
dace/codegen/targets/intel_fpga.py
dace/codegen/targets/mpi.py
dace/libraries/blas/nodes/batched_matmul.py
dace/libraries/blas/nodes/dot.py
dace/libraries/blas/nodes/gemm.py
dace/libraries/blas/nodes/gemv.py
dace/libraries/blas/nodes/transpose.py
dace/runtime/include/dace/reduction.h
dace/sdfg/nodes.py
dace/sdfg/sdfg.py
dace/sdfg/state.py
dace/sdfg/validation.py
dace/transformation/dataflow/mpi.py
dace/transformation/dataflow/stream_transient.py
dace/transformation/dataflow/tiling.py
dace/transformation/helpers.py
dace/transformation/interstate/fpga_transform_sdfg.py
dace/transformation/interstate/sdfg_nesting.py
dace/transformation/pattern_matching.py
tests/const_access_test.py
tests/default_storage_test.py

Assortment of minor fixes for improved user experience

---

dace/__init__.py
tests/short_decorator_test.py

This enables writing data-centric functions/programs in the most concise way possible:
```python
import dace
@dace
def myprog(A: dace.float32[20]):
return A + A
```

Allow "@dace" as a function decorator

---

dace/codegen/targets/cpp.py
dace/codegen/targets/cpu.py
dace/dtypes.py
dace/frontend/operations.py
dace/runtime/include/dace/reduction.h
dace/runtime/include/dace/types.h
dace/runtime/include/dace/view.h
tests/codegen/arraywrite_result_test.py
tests/codegen/atomic_xchg_test.py

Atomic operations return old values (if available) and atomic exchange

---

dace/codegen/codeobject.py

Fixes a bug with the ONNX frontend.

Fix default argument in environments

---

dace/sdfg/state.py

Removes propagation of type info from array to connector nodes.

---

dace/dtypes.py

Don't emit OpenCL vector type for vector length 1.

OpenCL Vector Length Fix

---

Jenkinsfile
README.md
dace/codegen/CMakeLists.txt

changed cmake_minimum_required  to 3.15

cmake fix for mac osx 10.14

---

dace/sdfg/sdfg.py
diode/sdfv.html
diode/templates/sdfv.html

Update DIODE to new format and renderer API

---

dace/transformation/helpers.py
tests/transformations/state_fission_test.py

Add state fission as transformation.helper.
Not sure how dealing with "parenting" problem. The nodes that are added to the newly created state, have a different parent. This is particular true for Nested SDFG.

State fission

---

dace/frontend/python/newast.py
dace/frontend/python/replacements.py
tests/python_frontend/nested_name_accesses_test.py

Fix names not being passed to nested SDFGs

---

dace/runtime/include/dace/cuda/halfvec.cuh
dace/runtime/include/dace/cuda/vectype.cuh
dace/runtime/include/dace/types.h
dace/runtime/include/dace/vector.h
tests/cuda_test.sh
tests/half_cudatest.py
tests/halfvec_cudatest.py

Support half vector types

---

dace/frontend/python/newast.py
tests/python_frontend/indirection_with_scalars_test.py

Enforcing proper SDFG semantics (indirection) and fix for #97.

Generate indirection for memlet subsets using scalar data (non-subscripted data names)

---

dace/frontend/python/newast.py
tests/python_frontend/multiple_nested_sdfgs_test.py

Fix for #438

---

dace/transformation/transformation.py

This should fix the problem with einsum not expanding properly to GPU code

Expansion schedule fix

---

dace/dtypes.py
dace/frontend/python/newast.py
dace/frontend/python/parser.py
dace/sdfg/validation.py
tests/numpy/list_globals_test.py
tests/python_frontend/call_sdfg_with_symbols_test.py

- fix calling SDFGs with symbols (Closes #447)
- Allow accessing symbols in lists or tuples from python frontend
- Skip element number validation when allow_oob is true

Frontend fixes

---

dace/dtypes.py
dace/frontend/python/newast.py
dace/sdfg/sdfg.py
dace/symbolic.py
tests/python_frontend/conditionals_test.py
tests/python_frontend/multiple_nested_sdfgs_test.py
tests/sdfg/scalar_to_symbol_test.py

The purpose of this PR is to make the handling of conditions consistent all over the AST (if/while statements).

Python frontend improved/consistent conditionals

---

dace/frontend/python/README.md
dace/frontend/python/python_supported_features.md

- updates on known issues (removed fixed issues)
- section about supported python versions
- section with main limitations
- section with numpy support

Updates to the documentation of the Python-Frontend

---

dace/sdfg/utils.py

Reduces noise. Upon Tal's request.

Removes 'merged_' prefix from merged maps.

---

dace/codegen/targets/fpga.py

Adds pragmas to do not consider loop carried dependencies that involve arrays read/written in map

Ivdep pragma

---

dace/codegen/targets/intel_fpga.py
tests/intel_fpga/autorun.py
tests/intel_fpga_test.sh

If kernels have no arguments that need to be passed from the host, generate them as `__attribute__((autorun))` kernels.

Intel Autorun Kernels

---

dace/codegen/CMakeLists.txt

Fixed wrong dependency specification that happened after introducing multiple kernels.

Fix dependency of xclbin target

---

dace/codegen/cppunparse.py
dace/codegen/targets/fpga.py
dace/codegen/targets/intel_fpga.py
tests/intel_fpga/constant_type_inference.py
tests/intel_fpga_test.sh
tests/type_inference_test.py

- Solves problem with type inference for constants
- reduces length of  function names

Intel fpga constant type inference

---

dace/memlet.py

Save the value of the parameter while constructing the memlet

Allow_oob parameter

---

dace/sdfg/state.py

Now correctly maps the defined symbols to their types.

defined_symbols: bugfix

---

dace/codegen/dispatcher.py
dace/codegen/targets/__init__.py
dace/codegen/targets/unroller.py
dace/dtypes.py
tests/codegen/unroller_test.py

To make the generated code pretty the argument 'skip_exit_node' was added to 'dispatch_subgraph(..)'.

Adds 'ScheduleType.Unrolled', codegen and test.

---

dace/transformation/dataflow/strip_mining.py
tests/transformations/tiling_number_of_tiles_test.py

- fixed range in the inner and outerloop.

strip_mining: fixed range bug for 'number_of_tiles'

---

dace/codegen/targets/fpga.py

With this PR we generate pragmas for loop carried dependencies also for pipeline scope, using a similar logic of the map scope.

Generate dep pragmas also for pipeline

---

dace/data.py
dace/frontend/python/replacements.py
dace/libraries/blas/blas_helpers.py
dace/libraries/blas/environments/intel_mkl.py
dace/libraries/blas/nodes/dot.py
dace/libraries/blas/nodes/gemv.py
dace/libraries/blas/nodes/matmul.py
dace/runtime/include/dace/cuda/vectype.cuh
dace/sdfg/sdfg.py
dace/subsets.py
dace/transformation/dataflow/redundant_array.py
tests/blas/nodes/blas_nodes_test.py
tests/blas/nodes/dot_test.py
tests/scalar_output_cudatest.py
tests/transformations/redundant_copy_test.py

Fix BLAS expansions for strided inputs

---

dace/codegen/compiler.py
dace/libraries/blas/environments/intel_mkl.py
dace/transformation/helpers.py
dace/transformation/interstate/gpu_transform_sdfg.py
tests/transformations/gpu_transform_test.py

Fix top-level allocation after GPU transformation

---

dace/codegen/targets/fpga.py

Solves #572 
By converting start/step/stop from sym expr to C++, we also resolve problems with ceiling/floor

Convert pipeline range from symexpr to C++

---

dace/codegen/compiled_sdfg.py
dace/codegen/targets/cpu.py
dace/transformation/dataflow/redundant_array.py

RedundantArray fix and invocation casting warning fixes

---

dace/codegen/targets/cpp.py
dace/dtypes.py
dace/frontend/python/newast.py
dace/frontend/python/parser.py
dace/libraries/blas/nodes/gemm.py
dace/libraries/blas/nodes/matmul.py
dace/library.py
dace/memlet.py
dace/sdfg/infer_types.py
dace/sdfg/nodes.py
dace/sdfg/propagation.py
dace/sdfg/scope.py
dace/sdfg/state.py
dace/subsets.py
dace/symbolic.py
dace/transformation/dataflow/strip_mining.py
dace/transformation/helpers.py
dace/transformation/interstate/sdfg_nesting.py
dace/transformation/transformation.py
tests/library/gemm_test.py

Fixes for GEMM library node and libnode schedules

---

dace/sdfg/sdfg.py
dace/transformation/dataflow/buffer_tiling.py
dace/transformation/dataflow/local_storage.py
dace/transformation/optimizer.py
dace/transformation/pattern_matching.py
dace/transformation/subgraph/gpu_persistent_fusion.py
dace/transformation/transformation.py
tests/buffer_tiling_test.py
tests/halfvec_cudatest.py

Transformation functions as methods

---

AUTHORS
dace/transformation/interstate/sdfg_nesting.py

- resolved a bug with symbol name clashes in `_check_strides`
- added myself to the list of authors

Bugfix: resolves symbol name clashes

---

dace/codegen/compiled_sdfg.py
dace/codegen/targets/common.py
dace/codegen/targets/cpp.py
dace/data.py
dace/frontend/common/op_repository.py
dace/frontend/python/memlet_parser.py
dace/frontend/python/newast.py
dace/frontend/python/replacements.py
dace/libraries/standard/nodes/reduce.py
dace/sdfg/sdfg.py
dace/subsets.py
dace/symbolic.py
tests/library/matmul_cudatest.py
tests/numpy/advanced_indexing_test.py
tests/numpy/common.py
tests/tasklet_test.py

NumPy Advanced Indexing Support

---

dace/libraries/lapack/__init__.py
dace/libraries/lapack/environments/__init__.py
dace/libraries/lapack/environments/cublas.py
dace/libraries/lapack/environments/intel_mkl.py
dace/libraries/lapack/environments/openblas.py
dace/libraries/lapack/nodes/__init__.py
dace/libraries/lapack/nodes/getrf.py
dace/libraries/lapack/nodes/getri.py
dace/libraries/lapack/nodes/getrs.py
dace/libraries/linalg/__init__.py
dace/libraries/linalg/environments/__init__.py
dace/libraries/linalg/environments/cublas.py
dace/libraries/linalg/environments/intel_mkl.py
dace/libraries/linalg/environments/openblas.py
dace/libraries/linalg/nodes/__init__.py
dace/libraries/linalg/nodes/inv.py
dace/libraries/mpi/__init__.py
dace/libraries/mpi/environments/__init__.py
dace/libraries/mpi/environments/mpi.py
dace/libraries/mpi/nodes/__init__.py
dace/libraries/mpi/nodes/bcast.py
dace/libraries/mpi/nodes/recv.py
dace/libraries/mpi/nodes/send.py
tests/library/lapack_getrf_test.py
tests/library/lapack_getri_test.py
tests/library/lapack_getrs_test.py
tests/library/linalg_inv_test.py
tests/library/mpi_send_recv_test.py

Mpi lib nodes

---

dace/transformation/interstate/loop_to_map.py
tests/transformations/loop_to_map_test.py

LoopToMap: Condition now addresses all memlets rather than CodeNode-adjacent memlets

LoopToMap condition fix

---

dace/codegen/targets/intel_fpga.py

Convert np types to C types

---

dace/transformation/auto_optimize.py

This is required when MKL is on the blocklist

Add both MKL and OpenBLAS to priority list

---

dace/memlet.py

Memlet's dynamic property is never anyhting other than a boolean value - This types it correctly

Set memlet's dynamic property to boolean

---

dace/codegen/compiler.py
dace/codegen/targets/cpp.py
dace/runtime/include/dace/cuda/cudacommon.cuh
dace/transformation/dataflow/__init__.py
dace/transformation/dataflow/map_fusion.py
dace/transformation/dataflow/redundant_array.py
dace/transformation/dataflow/warp_tiling.py
dace/transformation/helpers.py
dace/transformation/interstate/state_elimination.py
dace/transformation/subgraph/subgraph_fusion.py
tests/codegen/unparse_tasket_test.py
tests/transformations/view_redundant_array_test.py
tests/transformations/warp_tiling_test.py

Transformation improvements

---

dace/frontend/python/replacements.py

Numpy.where

---

dace/codegen/tools/type_inference.py
dace/frontend/python/newast.py
dace/frontend/python/replacements.py
dace/libraries/lapack/nodes/getrf.py
dace/libraries/lapack/nodes/getri.py
dace/libraries/lapack/nodes/getrs.py
tests/python_frontend/loops_test.py

- Fixed an issue where type-inference fails to return the dtype of a DaCe symbol.
- Fixed an issue where ranges with a step failed to parse.
- Fixed a casting issue with complex numbers and OpenBLAS.

Assortment of fixes related to symbols and complex numbers.

---

dace/codegen/targets/common.py
dace/codegen/tools/type_inference.py
dace/frontend/python/newast.py
dace/libraries/blas/nodes/gemm.py
dace/libraries/blas/nodes/matmul.py
dace/libraries/blas/nodes/transpose.py
tests/type_inference_test.py

This PR addresses issues related to mandelbrot2 and stockham_fft. The PR is made under the assumption that the method `symbolic.symstr` is converting symbolic expressions to cpp-compatible strings.

NPBench related fixes

---

dace/codegen/tools/type_inference.py
dace/transformation/interstate/sdfg_nesting.py
dace/transformation/interstate/state_fusion.py
tests/inlining_test.py

Further Transformation Fixes

---

dace/transformation/dataflow/prune_connectors.py

added check to not remove arrays from sdfgs unless all connectors are removed.

fixing prune connectors bug

---

dace/codegen/targets/mlir/utils.py
tests/mlir_tasklet_test.py

This PR introduces support for signed and unsigned integers and takes the changes to pyMLIR into account. 
Added some minor refactoring as well.

updates for pyMLIR changes

---

dace/sdfg/analysis/scalar_to_symbol.py

added check to remove candidate if any tasklet that should be made into an interstate edge could not be parsed as Python from C. Code translating C to Python refactored into separate function as it is used in two instances.

check in scal2sym promotion - fail gracefully

---

samples/fpga/gemm_systolic_vectorized.py

The `__main__` was outdated and didn't correctly use the input arguments. Fixed and moved to click.

Fix broken FPGA GEMM sample

---

dace/codegen/targets/fpga.py
dace/codegen/targets/intel_fpga.py
dace/codegen/targets/xilinx.py
tests/fpga/fpga_instrumentation_test.py
tests/fpga/kernel_detection_test.py

Kernel instrumentation for FPGA kernels was wrong for Xilinx kernels that had multiple processing elements.

Kernel instrumentation fix for single/multiple kernels

---

dace/libraries/stencil/__init__.py
dace/libraries/stencil/cpu.py
dace/libraries/stencil/stencil.py
dace/libraries/stencil/subscript_converter.py
tests/library/stencil/stencil_node_test.py

Merge an adapted version of the StencilFlow stencil library node into the main repo for more general use.

Stencil library node from StencilFlow

---

dace/transformation/dataflow/__init__.py
dace/transformation/dataflow/tasklet_fusion.py
tests/transformations/tasklet_fusion_test.py

This PR implements "simple" TaskletFusion, i.e. fusion of 2 Tasklets directly connected with each other.

Tasklet fusion

---

AUTHORS

More FPGA authors

---

dace/codegen/targets/cpu.py
dace/frontend/python/newast.py
dace/transformation/interstate/state_fusion.py

This PR contains an assortment of fixes for issues related to the FV3Core halo exchange.

Fixes for halo exchange

---

dace/frontend/python/newast.py
tests/numpy/subarray_in_nested_call_test.py

Fixes the case where data used in a nested call should be both input and output connector to the nested SDFG.

Nested inout connector

---

dace/codegen/dispatcher.py
dace/codegen/targets/cpp.py
dace/codegen/targets/cpu.py
dace/codegen/targets/cuda.py
dace/codegen/targets/fpga.py
dace/codegen/targets/framecode.py
dace/frontend/python/memlet_parser.py
dace/frontend/python/newast.py
dace/frontend/python/replacements.py
dace/sdfg/utils.py
dace/sdfg/validation.py
dace/transformation/dataflow/redundant_array.py
dace/transformation/helpers.py
dace/transformation/interstate/loop_to_map.py
dace/transformation/interstate/sdfg_nesting.py
dace/transformation/interstate/state_elimination.py
dace/transformation/subgraph/subgraph_fusion.py
tests/numpy/copies_and_views_test.py
tests/numpy/nested_call_subarray_test.py
tests/symbol_dependent_transients_test.py
tests/transformations/redundant_array_view_chains_test.py

This PR amends slicing of DaCe Arrays in the Python frontend so that it follows NumPy rules. For example, simple slicing should generate DaCe Views.

NumPy Copy/View Semantics

---

dace/data.py
dace/dtypes.py

Past changes broke the ability to pass torch tensors into SDFGs, this PR introduces a fix.

Fix torch tensor support

---

dace/memlet.py
dace/transformation/dataflow/redundant_array.py
dace/transformation/helpers.py
dace/transformation/interstate/sdfg_nesting.py
tests/numpy/nested_call_subarray_test.py

In transformations and memlet creation

Self-copy fixes

---

dace/frontend/python/newast.py
dace/transformation/interstate/sdfg_nesting.py
tests/numpy/copies_and_views_test.py
tests/transformations/nested_copies_among_connectors.py

Assortment of fixes to InlineSDFG that specifically target issues with nested edges between access nodes corresponding to connectors of the nested SDFG.

InlineSDFG fixes

---

dace/codegen/targets/cuda.py
tests/cuda_smem2d_test.py

Batch of fixes for GPU codegen

---

dace/codegen/targets/cpu.py
dace/sdfg/sdfg.py
dace/transformation/dataflow/prune_connectors.py
tests/npbench/floyd_warshall_test.py
tests/npbench/syrk_test.py
tests/transformations/prune_connectors_test.py

- Adds Floyd Warshall and Syrk Npbench kernels to CI tests
- Prune connectors: optionally removes unused containers
- View: declare view using the appropriate method

Npbench tests

---

dace/libraries/standard/nodes/reduce.py
tests/library/reduce_test.py

* Work with multiple dimensions
* Work with arbitrary WCRs

Fix sequential reduction expansion

---

dace/frontend/python/common.py
setup.py

Fix Python 3.6 compatibility

---

dace/codegen/targets/framecode.py
dace/frontend/python/newast.py
dace/frontend/python/replacements.py
dace/sdfg/replace.py
dace/sdfg/sdfg.py
dace/sdfg/validation.py
dace/symbolic.py
dace/transformation/dataflow/redundant_array.py
dace/transformation/interstate/multistate_inline.py
dace/transformation/interstate/sdfg_nesting.py
tests/constant_array_test.py
tests/numpy/array_creation_test.py

Support using constants as data descriptors

---

dace/codegen/codegen.py
dace/codegen/compiled_sdfg.py
dace/codegen/targets/cuda.py
dace/codegen/targets/framecode.py
dace/codegen/targets/intel_fpga.py
dace/codegen/targets/mpi.py
dace/codegen/targets/xilinx.py
dace/sdfg/sdfg.py
tests/codegen/init_contains_scalars.py

Adds SDFG.init_signature that is used for code generation.

Remove scalars from the SDFG init signature.

---

dace/transformation/interstate/loop_to_map.py
tests/transformations/loop_to_map_test.py

Solves one of the issues in #909

LoopToMap, pass constant_prop to nested sdfg

---

dace/frontend/python/newast.py
dace/sdfg/propagation.py
dace/sdfg/validation.py
tests/memlet_propagation_test.py

Dynamic memlet propagation

---

dace/codegen/targets/xilinx.py
tests/fpga/xilinx_interstate_preprocessing.py

Xilinx preprocess fix

---

dace/config_schema.yml
dace/frontend/python/newast.py
dace/libraries/blas/environments/intel_mkl.py
dace/sdfg/sdfg.py
dace/sdfg/utils.py
dace/transformation/dataflow/redundant_array.py
tests/python_frontend/method_test.py

Fix issue #971

---

dace/frontend/python/replacements.py
tests/numpy/array_creation_test.py

Adds support for numpy.arange. The 'like` keyword is currently not supported.

Support for numpy.arange

---

dace/transformation/passes/scalar_to_symbol.py
tests/sdfg/scalar_to_symbol_test.py

Fix for #997

---

dace/frontend/python/newast.py
dace/frontend/python/preprocessing.py
tests/python_frontend/callback_autodetect_test.py

through argument flattening and marshalling

Support literal lists, tuples, sets, and dictionaries in callbacks

---

dace/codegen/targets/cpu.py
dace/dtypes.py
dace/properties.py
dace/registry.py
dace/sdfg/infer_types.py
dace/sdfg/nodes.py
dace/serialize.py
requirements.txt
setup.py
tests/openmp_test.py
tests/schedule_inference_test.py

Experimental: Optional OpenMP properties

---

dace/codegen/targets/cpu.py
dace/dtypes.py
dace/properties.py
dace/registry.py
dace/sdfg/infer_types.py
dace/sdfg/nodes.py
dace/serialize.py
requirements.txt
setup.py
tests/openmp_test.py
tests/schedule_inference_test.py

This PR adds direct support to Maps for OpenMP pragma attributes, such as:
- num_threads
- schedule {static, dynamic, guided}
- chunk-size

Adding OMP attributes to Maps

---

dace/codegen/dispatcher.py
dace/dtypes.py
dace/frontend/python/newast.py
dace/symbolic.py
tests/codegen/allocation_lifetime_test.py

Various fixes to parsing and codegen

---

dace/frontend/python/astutils.py
dace/frontend/python/newast.py
dace/frontend/python/replacements.py
dace/libraries/mpi/nodes/allgather.py
dace/libraries/mpi/nodes/allreduce.py
dace/libraries/mpi/nodes/bcast.py
dace/libraries/mpi/nodes/dummy.py
dace/libraries/mpi/nodes/gather.py
dace/libraries/mpi/nodes/irecv.py
dace/libraries/mpi/nodes/isend.py
dace/libraries/mpi/nodes/node.py
dace/libraries/mpi/nodes/recv.py
dace/libraries/mpi/nodes/redistribute.py
dace/libraries/mpi/nodes/reduce.py
dace/libraries/mpi/nodes/scatter.py
dace/libraries/mpi/nodes/send.py
dace/libraries/mpi/nodes/wait.py
dace/libraries/standard/nodes/code.py
dace/sdfg/graph.py
dace/sdfg/nodes.py
dace/sdfg/state.py
dace/sdfg/utils.py
dace/transformation/interstate/trivial_loop_elimination.py
dace/transformation/passes/analysis.py
dace/transformation/passes/dead_dataflow_elimination.py
dace/transformation/passes/dead_state_elimination.py
dace/transformation/passes/scalar_to_symbol.py
tests/passes/dead_code_elimination_test.py
tests/python_frontend/constant_and_keyword_args_test.py

Simplify passes (2): Dead Code Elimination

---

dace/transformation/passes/analysis.py
dace/transformation/passes/array_elimination.py
tests/passes/array_elimination_test.py

Implement array elimination pass (covers redundant copies/views, merge source/sink arrays).

Simplify Passes (4): Array Elimination

---

dace/frontend/python/newast.py
dace/transformation/interstate/multistate_inline.py
tests/python_frontend/callback_autodetect_test.py

Skip unused callbacks in nested SDFGs

---

dace/codegen/targets/cpp.py
tests/fpga/reduce_fpga_test.py

Deal with scalar as nsdfg FPGA arguments

---

dace/frontend/python/parser.py
tests/python_frontend/multiple_nested_sdfgs_test.py

Fixes issue #1050 and potential regressions in the CI

Fixes reuse of a cached SDFG in a nested parsing context

---

dace/codegen/compiled_sdfg.py
dace/codegen/targets/cpp.py
dace/codegen/targets/cpu.py
dace/codegen/targets/cuda.py
dace/codegen/targets/framecode.py
dace/config_schema.yml
dace/data.py
dace/dtypes.py
dace/frontend/python/replacements.py
dace/libraries/standard/nodes/reduce.py
dace/subsets.py
dace/transformation/auto/auto_optimize.py
dace/transformation/interstate/loop_detection.py
dace/transformation/passes/transient_reuse.py
tests/codegen/cuda_mempool_test.py
tests/numpy/builtins_test.py
tests/numpy/reductions_test.py
tests/python_frontend/callback_autodetect_test.py

GPU Memory Pool, strings, and minor fixes

---

dace/frontend/python/newast.py
tests/python_frontend/callback_autodetect_test.py

Python Frontend: Add SDFG arrays to defined variables

---

dace/frontend/python/replacements.py

Including 1D "transposition", which does not do anything

Fix multidimensional transpose

---

dace/dtypes.py
dace/frontend/python/common.py
dace/frontend/python/replacements.py
dace/serialize.py
tests/python_frontend/binop_replacements_test.py
tests/python_frontend/string_test.py

- Add comparison methods to StringLiteral
- Correct and add test

Correct StringLiteral comparison and add test

---

dace/memlet.py
dace/transformation/dataflow/redundant_array.py
tests/transformations/redundant_copy_test.py

Redundant array removal fix

---

dace/frontend/python/interface.py
dace/frontend/python/parser.py
dace/sdfg/sdfg.py
doc/general/debugging.rst
tests/indirection_test.py
tests/python_frontend/dace_program_test.py

Avoids recreating SDFGs / regenerating code / recompiling them
Also removes the now-unnecessary .sdfgl file

Convenience SDFG Optimization API

---

dace/codegen/targets/intel_fpga.py
tests/npbench/polybench/jacobi_1d_test.py

Pass nested SDFG argument as scalar when they are actually scalar

Intel FPGA: scalar NSDFG arg passed by value

---

dace/codegen/targets/fpga.py
dace/codegen/targets/intel_fpga.py
dace/codegen/targets/xilinx.py

Check fpga vendor is supported

---

dace/codegen/instrumentation/likwid.py

This PR:
- Adds a missing env variable LIKWID_PERF_PID pointing to the current PID when using the perf_event backend. This resolves the error message "setup of counters of thread 0 failed".
- changes the default backend of LIKWID to perf_event. This means likwid can now be built and installed locally without sudo rights, i.e., no change of MSR files ownership and no change of the linux default perf_event_paranoid=2
With the default perf_event_paranoid, the access to some counters is however denied. The sysadmin would have to lower this level

Changed default backend of likwid instrumentation

---

dace/sdfg/sdfg.py

Replaces _find_new_name logic with data.find_new_name implementation.

fix to use data.find_new_name in _find_new_name

---

dace/codegen/targets/cuda.py
tests/cuda_highdim_kernel_test.py

Fixes an important GPU code generator bug where multidimensional kernels without explicit thread block maps will not work correctly for a 3rd block size argument.

Fix implicit block size division on high dimensional GPU kernels

---

dace/codegen/CMakeLists.txt
dace/codegen/common.py
dace/codegen/compiler.py
dace/codegen/instrumentation/data/data_dump.py
dace/codegen/instrumentation/gpu_events.py
dace/codegen/targets/cpp.py
dace/codegen/targets/cuda.py
dace/codegen/tools/get_hip_arch.cpp
dace/config_schema.yml
dace/libraries/blas/environments/__init__.py
dace/libraries/blas/environments/rocblas.py
dace/libraries/blas/include/dace_rocblas.h
dace/libraries/blas/nodes/gemm.py
dace/runtime/include/dace/cuda/halfvec.cuh
doc/optimization/gpu.rst
samples/optimization/matmul.py
tests/cuda_grid_test.py

AMD-related fixes and rocBLAS GEMM

---

dace/frontend/python/newast.py
tests/python_frontend/augassign_wcr_test.py

Fix augmented assignment on scalar in condition

---

samples/distributed/jacobi_1d.py

The sample scripts under `samples/distributed` have output logs (like time spent, validation correctness) expcept for the `jacobi_1d.py`. It would be beneficial for us to add time logs and validation output for this script as well.
Added time logs and validation results in `jacobi_1d.py`.
I have tested the result, a sample output running under 2 processes would be (the format is just like other scripts result):
```
Median is 2ms
=======Validation=======
OK
```

Standardize jocobi_1d scpripts as other distributed samples

---

dace/transformation/dataflow/__init__.py
dace/transformation/dataflow/gpu_grid_stride_tiling.py
tests/transformations/gpu_grid_stride_tiling_test.py

Implements a transformation that tile two nested maps into GPU grid-strided pattern.

GPU Grid-Strided Tiling

---

.github/workflows/general-ci.yml
setup.py

Add support for Python 3.11

---

dace/codegen/targets/cpp.py
tests/python_frontend/indirections_test.py

This PR tests and alternative fix for #1300.

Alternative fix for 1300

---

dace/sdfg/state.py
tests/sdfg/state_test.py

Discovered that my newly added code for computing the read and write sets fails of an out edge needs to be remove due to 2 incoming edges it throws an error as it tries to remove the same edge twice

Added testcase and fix

---

dace/transformation/auto/fpga.py

Allow the user to specify the targeted type of memory when performing automatic buffer interleaving for FPGA.
Addresses issues raised in #1351

Have memory type as argument for fpga auto interleave

---

tests/fortran/cloudsc/generated_sdfgs.py

Not sure about this one to be honest. The whole specialization part seems a bit fragile to me. I think it's a valid use-case and preferably DaCe would provide better support for this. But investigating a clean solution might be a bit time-consuming. I think for now it might be better to move forward with something that works...

Basic fix for validation error after specialization

---

dace/cli/sdfv.py

While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [sdfv.py](https://github.com/spcl/dace/blob/master/dace/cli/sdfv.py#L44), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of mktemp with `mkstemp`.
Replaced `mktemp()` method with `mkstemp()`
- https://www.github.com/invesalius/invesalius3/pull/679
- https://www.github.com/Azure/azure-linux-extensions/pull/1816
- …

Fixed Improper Method Call: Replaced `mktemp`

---

dace/sdfg/sdfg.py
dace/sdfg/validation.py

Compress the SDFG generated when failing/invalid for larger codebase

---

.github/workflows/fpga-ci.yml
tests/fpga/jacobi_fpga_test.py
tests/fpga/map_unroll_processing_elements_test.py
tests/fpga/matmul_test.py
tests/fpga/reduce_fpga_test.py
tests/fpga/simple_systolic_array_test.py
tests/fpga/vec_sum_test.py
tests/npbench/polybench/gemm_npbench_test.py
tests/npbench/polybench/k2mm_test.py
tests/npbench/polybench/k3mm_test.py
tests/npbench/polybench/lu_test.py
tests/npbench/polybench/trisolv_test.py

FPGA CI Update

---

dace/codegen/targets/cpu.py

Fix for const references

---

dace/sdfg/utils.py

The main issue was a typo were `src` was accessed instead of `dst`.

Fixed edge consolidation

---

dace/viewer/templates/sdfv.html

SDFV has been updated to include the distribution / compiled files again through a separate `dist` branch. This way pulling DaCe or installing it through pip does not require any additional builds to make use of the viewer. Additionally, paths have been corrected (the HTML template used by the `sdfv` CLI command was severely outdated).
(Closes #100)

Updated SDFV and Corresponding HTML Template

---

dace/codegen/control_flow.py
dace/codegen/targets/framecode.py
dace/frontend/python/newast.py
dace/sdfg/analysis/cfg.py
dace/sdfg/analysis/schedule_tree/sdfg_to_tree.py
dace/sdfg/performance_evaluation/operational_intensity.py
tests/codegen/control_flow_detection_test.py
tests/schedule_tree/schedule_test.py

This PR fixes incorrect handling of control flow detection that leads to infinite loops. Branch merge detection is refactored out and reused across the codebase, fixing the issue and also fixing goto statement existence in Schedule Trees.

Fix infinite loop with control flow blocks

---

dace/sdfg/validation.py

Add a validation test for race conditions induced by assigning and reading the same value in a single interstate edge. For example: `i = j + 1; j = ...`

Inter-state edge assignment race test

---

dace/transformation/interstate/multistate_inline.py

The `can_be_applied()` function did not consider the symbol map when the shape of the arrays were compared. This commit fixes this behaiour by first appling a replacing step before the comparisson.
Furthermore, the commit removes all the commented out code.

Updated `InlineMultistateSDFG`

---

tutorials/codegen.ipynb

Quick fix follow-up from https://github.com/spcl/dace/pull/1706 which left a broken notebook.

Fix broken codegen tutorial

---

dace/cli/sdfgcc.py
dace/cli/sdfv.py
dace/codegen/compiled_sdfg.py
dace/codegen/compiler.py
dace/codegen/cppunparse.py
dace/codegen/tools/type_inference.py
dace/dtypes.py
dace/memlet.py
dace/properties.py
dace/runtime/include/dace/stream.h
dace/sdfg/graph.py
dace/sdfg/propagation.py
dace/sdfg/sdfg.py
dace/sdfg/utils.py
dace/sdfg/validation.py
dace/subsets.py
dace/symbolic.py
dace/transformation/dataflow/redundant_array.py
dace/transformation/dataflow/tasklet_fusion.py
dace/transformation/helpers.py
dace/transformation/interstate/loop_to_map.py
dace/transformation/interstate/multistate_inline.py
dace/transformation/interstate/sdfg_nesting.py
dace/transformation/interstate/state_fusion.py
dace/transformation/passes/analysis/analysis.py
dace/transformation/passes/pattern_matching.py
dace/transformation/passes/prune_symbols.py
dace/transformation/passes/scalar_to_symbol.py
tests/transformations/tasklet_fusion_test.py

* Various minor code generation and runtime fixes
* Minor API improvements to CompiledSDFG, sdfg.view(), and subset offsetting
* Minor memlet propagation fix
* Various simplify pass fixes that pertain to use of views, references, and tasklets with side effects
* Symbolic support for shift and ternary expressions (fixes #1315)
* Pass permissiveness into transformations

Various stability improvements and convenience APIs

---

dace/frontend/python/parser.py
dace/sdfg/sdfg.py

This PR adds additional API calls and fields as requested by DaCe users. This includes:
* `SDFG.auto_optimize`
* `SDFG.regenerate_code`
* `SDFG.as_schedule_tree`

SDFG API additions for version 1.0

---

dace/frontend/python/newast.py
dace/sdfg/sdfg.py
tests/npbench/misc/mandelbrot1_test.py
tests/npbench/misc/mandelbrot2_test.py
tests/python_frontend/nested_name_accesses_test.py

Fix temporary transient counter during Python parsing of nested calls

---

tests/fortran/prune_unused_children_test.py
tests/fortran/recursive_ast_improver_test.py

Just to make sure that this is handled correctly at the parsing+pruning level.

[Multi SDFG, Fortran] Add a test case where "a module contains a subroutine contains another subroutine" etc.

---

dace/frontend/fortran/fortran_parser.py
tests/fortran/ast_desugaring_test.py

Specifically, handle the array cases better. There are a ton of other things to improve in there, so it's not a solved problem by any means -- just one step more correct than before.

[Multi SDFG, Fortran] Have a better type matching to select concrete implementations for generic interfaces.

---

dace/frontend/fortran/fortran_parser.py
tests/fortran/prune_unused_children_test.py

Not integrated anywhere yet. Just changed the tests as a proof of concept that the FParser AST stays the same with the new pruning.

[Multi SDFG, Fortran] Add a new, shorter pruning function that removes any function, subroutine, types etc. that are not used.

---

dace/frontend/fortran/fortran_parser.py
dace/frontend/fortran/icon_config_propagation.py

From now, total ban on hardcoding paths in DaCe code.

Remove all hardcoded paths from Fortran frontend

---

dace/frontend/fortran/ast_transforms.py
dace/frontend/fortran/fortran_parser.py
dace/frontend/fortran/intrinsics.py

This reverts commit 9d592a47bb35259afc50a0f69007a5afee0d7b04.

Revert "Make merge great again" which broke the fortran frontend (especially for ECRAD)

---

dace/frontend/fortran/ast_desugaring.py
dace/frontend/fortran/ast_internal_classes.py
dace/frontend/fortran/ast_transforms.py
dace/frontend/fortran/config_propagation_data.py
dace/frontend/fortran/fortran_parser.py
dace/frontend/fortran/icon_config_propagation.py
tests/fortran/array_dims_config_injetor_test.py
tests/fortran/fortran_test_helper.py

This must happen after the intrinsic transforms, since they replace the intrinsic calls with the extra variables.

[Multi SDFG, Fortran] Inject `size()` related configs in the internal AST.

---

dace/frontend/fortran/ast_components.py
dace/frontend/fortran/ast_desugaring.py
dace/frontend/fortran/ast_transforms.py
dace/frontend/fortran/fortran_parser.py
tests/fortran/ast_desugaring_test.py
tests/fortran/prune_unused_children_test.py

Now all `present()` calls are gone too. Post-pruning 8.6k LoC remains.

[Multi SDFG, Fortran] 1) Refine the "practically const arg => const" 2) Add a "practically const global var => const" 3) Fix the pruning test

---

dace/frontend/fortran/ast_desugaring.py

1) There were some cases not handled that was found in the tests.
2) This is mostly cosmetic, but harmless pruning. Pruned code is at about ~8.3k LoC after this.

[Multi SDFG, Fortran] 1) Handle part-refs better in the type deduction. 2) Cleanup empty modules and unused local variables inside functions.

---

dace/frontend/fortran/ast_transforms.py
dace/frontend/fortran/ast_utils.py
dace/frontend/fortran/fortran_parser.py
dace/frontend/fortran/intrinsics.py

Of course we cannot enable it permanently right now because it breaks all the test. But still helps to raise at least some flags before SDFG construction begins, when enabled.

[f2dace-dev, fortran] Add some basic validations for mistakes that have shown up before.

---

dace/codegen/targets/framecode.py
dace/sdfg/utils.py

Adds extraneous SDFGStates before/after CFGs when inferring the allocation lifetime.

CFG (post)dominator SDFGStates

---

dace/sdfg/sdfg.py
dace/sdfg/validation.py
dace/transformation/transformation.py

Backport of PR https://github.com/spcl/dace/pull/1917.

Fix typos (backport)

---

dace/codegen/codegen.py

Currently, the generated `.h` is "uncompilable" together with the generate `.cpp`. Here we are:
1. Declaring the functions in the header the exact same way as the definition inside.
2. Putting everything (including the struct definition that alexnick added yesterday) in the header behind a header guard.
TODO later:
- We should remove the struct definition in the `.cpp` and include the `.h`.

[f2dace/dev] Generate a compatible header.

---

tests/fortran/type_array_test.py

~1. Validation is disabled because that's what breaks. But if we disable it the actual computation graph turns out just fine.
2. A C++ change is needed, because my `clang++` is convinced that it's not right.~

[f2dace/dev, fortran] Better type array test that actually tests things beyond compilation

---

.github/workflows/fpga-ci.yml
.github/workflows/general-ci.yml
.github/workflows/gpu-ci.yml
.github/workflows/heterogeneous-ci.yml
.github/workflows/pyFV3-ci.yml

Cancel in-progress CI builds if a new PR commit was pushed

---

doc/design/README.md
doc/design/codegen.md
doc/design/descriptors.md
doc/design/frontend.md

This PR contains significant upcoming changes to the design of the DaCe framework in version 2.0 in the form of design documents.

Design Documents

---

dace/transformation/passes/symbol_propagation.py
tests/passes/symbol_propagation_test.py

This PR fixes a bug in SymbolPropagation regarding scalars in interstate edges and adds a regression test.

Bugfix SymbolPropagation

---

dace/subsets.py
dace/symbolic.py

Some operations that operates on symbols are very slow.
This PR optimizes some of the usage.

Optimizations Related to Symbols

---

dace/transformation/passes/dead_dataflow_elimination.py

Fix DDE applying incorrectly on pointer / size > 1 tasklet data
